import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {RunService} from '../server/runs.mjs';
import {RunStore,acquireDirectoryLock} from '../server/storage.mjs';
import {ProjectStore} from '../server/projects.mjs';
import {PatenticsSource,parseDetail} from '../server/patentics.mjs';
import {newProject,mergeRun,projectTask,freezeReport,migrateProject,reportSections} from '../core/project.mjs';
import {planEvidenceBatches} from '../core/evidence-selection.mjs';
import {exportProjectArchive,readArchive} from '../server/archive.mjs';
import {zipFiles} from '../core/docx.mjs';
import {buildStrategy,normalizeRecords,createTask,AppError,restoreWorkspace,hash} from '../core/engine.mjs';
import {attachAnalysis,modelState} from '../core/model-analysis.mjs';
import {modelEvidenceInput,classifyModelError} from '../server/models.mjs';
const temp=()=>mkdtemp(join(tmpdir(),'xlab-v03-'));
test('V03 retries preserve one logical round and count failed model attempts',()=>{let p=newProject('液氢');const first={run_id:'first',input:{kind:'search',project_id:p.project_id,strategy:{}},actual_query:{sq:'液氢'},status:'partial',api_calls:6,model_calls:1,task:{records:[]}};p=mergeRun(p,first);p=mergeRun(p,{...first,run_id:'retry',retry_of:'first',previous_api_calls:6,api_calls:8,model_calls:2});assert.equal(p.rounds.length,1);assert.equal(p.rounds[0].api_calls,8);assert.deepEqual(p.run_history.map(r=>r.api_calls),[6,2]);assert.equal(projectTask(p).cost.model_calls,3);assert.equal(mergeRun(p,first).run_history.length,2);assert.equal(p.last_run.run_id,'retry');});
test('V03 new analysis archives prior human decisions instead of reapplying IDs',()=>{const p=newProject('液氢');p.analyses=[{run_id:'old'}];p.reviews={'model-finding-1':{state:'adopted'}};const next=mergeRun(p,{run_id:'new',input:{kind:'analyze'},task:{model_analysis:{}},model_calls:1});assert.deepEqual(next.reviews,{});assert.equal(next.review_history[0].analysis_run_id,'old');assert.equal(next.review_history[0].reviews['model-finding-1'].state,'adopted');});
test('V03 model receives original evidence but no repeated transport metadata',()=>{const text='原文内容';const input={records:[{record_id:'p1',title:'专利',evidence:[{evidence_id:'e1',field:'claims',text,source_url:'internal-path',checksum:'local-only'}]}]};const compact=modelEvidenceInput(input);assert.equal(compact.records[0].evidence[0].text,text);assert(!JSON.stringify(compact).includes('internal-path'));assert.equal(input.records[0].evidence[0].checksum,'local-only');});
const strategy={...buildStrategy('液氢'),object_terms:['液氢'],focus_terms:[]};
const xml=(n=1)=>`<Patent><PN>CN${n}A</PN><Title>液氢储罐</Title><Abstract>液氢储罐使用换热器调节压力。</Abstract><Claims><Claim name="1" dep="0">一种液氢储罐，包括换热器和压力传感器。</Claim></Claims><Description><Section id="1">换热器与储罐连接。</Section></Description></Patent>`;
const record=(n=1)=>normalizeRecords([parseDetail(xml(n),{publication_number:`CN${n}A`,title:'液氢储罐'},'cnapp',strategy)],'live').records[0];
const task=()=>{const t=createTask('液氢',normalizeRecords([record()],'live'),strategy);return t;};
const output=records=>({routes:[{label:'换热器',description:'原文出现换热器',evidence_ids:[records[0].evidence[0].evidence_id]}],findings:[{text:records[0].evidence[0].text,type:'direct_quote',quotes:[{evidence_id:records[0].evidence[0].evidence_id,quote:records[0].evidence[0].text}],scope:'当前原文',limitations:'需复核'}],questions:[]});
async function terminal(s){for(let i=0;i<500;i++){if(!s.active)return;await new Promise(r=>setTimeout(r,5));}throw Error('did not settle');}
test('V03 concurrent retry and start share one lock',async()=>{const s=new RunService(await temp(),{models:{generate:async(k,i,p,signal)=>new Promise((resolve,reject)=>signal.addEventListener('abort',()=>reject(new AppError('CANCELLED','取消'))))}});const r={run_id:'run-'+randomUUID(),created_at:new Date().toISOString(),status:'failed',input:{topic:'液氢',strategy,provider:'codex',kind:'analyze'},task:task(),requests:[],warnings:[],api_calls:0,model_calls:0};await s.store.save(r);const result=await Promise.allSettled([s.retry(r.run_id),s.retry(r.run_id)]);assert.equal(result.filter(r=>r.status==='fulfilled').length,1);assert.equal(result.find(r=>r.status==='rejected').reason.code,'RUN_CONFLICT');await s.cancel(s.active.run_id);await terminal(s);});
test('V03 same idempotency key reuses run without duplicate model',async()=>{let calls=0;const s=new RunService(await temp(),{models:{generate:async(k,i)=>{calls++;return {output:output(i.records),metadata:{provider:'codex',model:'test'}};}}});const input={kind:'analyze',topic:'液氢',strategy,task:task(),idempotency_key:'same-request'};const first=await s.start(input);await terminal(s);const second=await s.start(input);assert.equal(first.run_id,second.run_id);assert.equal(calls,1);});
test('V03 source identity survives acquisition retry',async()=>{const s=new RunService(await temp()),r=record();r.source_metadata.source_run_id='run-'+randomUUID();const run={run_id:'run-'+randomUUID(),input:{topic:'液氢',strategy,database:'cnapp'},acquired:[r],candidates:[],requests:[],api_calls:1,model_calls:0};assert.equal(s.makeTask(run).records[0].source_metadata.source_run_id,r.source_metadata.source_run_id);});
test('V03 all detail failures do not complete successfully',async()=>{const root=await temp(),s=new RunService(root,{sourceFactory:()=>new PatenticsSource({key:'mock',store:new RunStore(root),limiter:{reserve:async()=>{}},fetchImpl:async url=>new URL(url).pathname.endsWith('search')?new Response('<Result><Total>1</Total><PatentList><Patent><p>CN1A</p><t>液氢</t></Patent></PatentList></Result>'):new Response('',{status:500})})});const r=await s.start({kind:'search',topic:'液氢',strategy,analyze:false});await terminal(s);const saved=await s.store.get(r.run_id);assert.equal(saved.status,'failed');assert.equal(saved.retrieval_outcome,'failed');assert.equal(saved.api_calls,3);});
test('V03 directory lock prevents recovery by another service instance',async()=>{const root=await temp(),release=await acquireDirectoryLock(root);await assert.rejects(()=>acquireDirectoryLock(root),e=>e.code==='STATE_LOCKED');await release();const second=await acquireDirectoryLock(root);await second();});
test('V03 project CAS preserves newest notes and rejects delayed writer',async()=>{const store=new ProjectStore(await temp()),p=await store.create('液氢');const next=await store.update(p.project_id,{revision:p.revision,notes:{'pat-CN1A':'first'}});await assert.rejects(()=>store.update(p.project_id,{revision:p.revision,notes:{'pat-CN1A':'old'}}),e=>e.code==='PROJECT_CONFLICT');assert.equal((await store.get(p.project_id)).notes['pat-CN1A'],'first');assert.equal(next.revision,p.revision+1);});
test('V03 repeat publication preserves both source versions and A/B separately',()=>{let p=newProject('液氢');const make=(id,r)=>({run_id:id,input:{kind:'search',topic:'液氢',strategy},created_at:new Date().toISOString(),requests:[],task:{records:[r]},candidates:[],api_calls:1,status:'completed'});p=mergeRun(p,make('first',record()));const changed=record();changed.source_metadata.raw_sha256='a'.repeat(64);p=mergeRun(p,make('second',changed));assert.equal(p.records.length,1);assert.equal(p.source_conflicts.length,1);assert.equal(p.source_conflicts[0].previous.source_metadata.raw_sha256,record().source_metadata.raw_sha256);const b={...record(),record_id:'pat-CN1B',publication_number:'CN1B'};p=mergeRun(p,make('third',b));assert.equal(p.records.length,2);});
test('V03 project fingerprints invalidate analysis after excluding evidence',()=>{const p=newProject('液氢');p.records=[record()];p.draft.strategy=strategy;const t=projectTask(p);p.analyses.push({model_analysis:attachAnalysis(t,output(t.records),{provider:'codex',model:'test'}).model_analysis});assert.equal(modelState(projectTask(p)),'current');p.excluded=['pat-CN1A'];assert.equal(modelState(projectTask(p)),'stale');});
test('V03 model selection covers fields and never exceeds budget',()=>{const records=Array.from({length:20},(_,i)=>record(i+1)),batches=planEvidenceBatches(records);assert.equal(batches.length,4);for(const b of batches){assert(b.characters<=24000);assert.equal(b.records.length,5);for(const r of b.records)assert.deepEqual(new Set(r.evidence.map(e=>e.field)),new Set(['abstract_excerpt','claims','description']));}assert.throws(()=>planEvidenceBatches([...records,record(21)]),/20/);});
test('V03 failed batch retry skips successful model batches and data retrieval',async()=>{let calls=0,fail=true;const s=new RunService(await temp(),{models:{generate:async(k,i)=>{calls++;if(calls===2&&fail)throw new AppError('MODEL_TIMEOUT','mock timeout');return {output:output(i.records),metadata:{provider:'codex',model:'test'}};}}});const t=task();t.records=Array.from({length:6},(_,i)=>record(i+1));const r=await s.start({kind:'analyze',topic:'液氢',strategy,task:t});await terminal(s);assert.equal((await s.store.get(r.run_id)).analysis_batches[0].status,'completed');fail=false;const retry=await s.retry(r.run_id);await terminal(s);assert.equal((await s.store.get(retry.run_id)).status,'completed');assert.equal(calls,4);});
test('V03 full archive restores XML and rejects tampered manifest',async()=>{const store=new RunStore(await temp()),p=newProject('液氢');p.records=[record()];await store.asset(xml());const archive=await exportProjectArchive(p,store),restored=readArchive(Buffer.from(archive));assert.equal(restored.assets.length,1);assert.equal(restored.assets[0].toString(),xml());const bad=Buffer.from(archive),index=bad.indexOf(Buffer.from('液氢'));bad[index]=0x41;assert.throws(()=>readArchive(bad),/校验和/);});
test('V03 archive rejects traversal paths before importing anything',()=>{const zip=zipFiles({'../bad.json':'{}','project.json':'{}','manifest.json':'{}'});assert.throws(()=>readArchive(Buffer.from(zip)),/路径/);});
test('V03 report version freezes edits and invalid reference cannot export',()=>{const p=newProject('液氢');p.records=[record()];p.report_draft.sections=[{id:'scope',title:'人工判断',text:'用户编辑\n['+p.records[0].evidence[0].evidence_id+']'}];const one=freezeReport(p);p.reports.push(one);assert.equal(freezeReport(p).report_id,one.report_id);p.report_draft.sections[0].text+='修改';const two=freezeReport(p);assert.equal(two.version,2);assert(!one.markdown.includes('修改'));p.report_draft.sections[0].text='[ev-not-owned]';assert.throws(()=>freezeReport(p),/引用/);});
test('V03 legacy all-excluded restore has consistent counts and preserves notes',()=>{const t=task(),id=t.records[0].record_id;t.records=[];const raw={schema:2,topic:'液氢',strategy,dataset:{records:[record()]},task:t,excluded:[id],notes:{[id]:'用户排除理由'}};const r=restoreWorkspace(raw);assert.equal(r.task.query.returned_count,0);assert.equal(r.task.stats.count,0);assert.equal(r.notes[id],'用户排除理由');const p=migrateProject(raw);assert.equal(p.notes[id],'用户排除理由');assert.deepEqual(p.excluded,[id]);});

test('V03 legacy evidence identity and edited report survive migration',()=>{const r=record();r.evidence=r.evidence.map(e=>({...e,evidence_id:`ev-${r.publication_number}-${hash(e.field+'|'+e.text)}`}));const t=createTask('液氢',normalizeRecords([r],'live'),strategy);assert.equal(t.records[0].evidence[0].evidence_id,r.evidence[0].evidence_id);const p=migrateProject({schema:2,topic:'液氢',strategy,dataset:{records:[r]},task:t,excluded:[],notes:{},edit:{title:'旧标题',introduction:'旧说明',conclusion:'旧判断'}});assert.equal(p.report_draft.title,'旧标题');assert(p.report_draft.sections.some(s=>s.text.includes('旧判断')));});
 test('V03 report cannot promote unreferenced comparison or another patent citation',()=>{const p=newProject('液氢');p.records=[record(),record(2)];p.comparison.record_ids=p.records.map(r=>r.record_id);p.comparison.cells['pat-CN1A|核心结构']='无来源结论';assert.throws(()=>freezeReport(p),/来源/);p.comparison.cells['pat-CN1A|核心结构']='['+p.records[1].evidence[0].evidence_id+']';assert.throws(()=>freezeReport(p),/对应专利/);p.comparison.cells['pat-CN1A|核心结构']='人工来源：研究者提供的2026年试验记录，仅作待核验备注';assert(freezeReport(p));});
 test('V03 archive truncated after local entries is rejected',async()=>{const store=new RunStore(await temp()),p=newProject('液氢');const archive=Buffer.from(await exportProjectArchive(p,store));assert.throws(()=>readArchive(archive.subarray(0,archive.length-22)),/尾部/);});
 test('V03 repeated next page stops before detail requests',async()=>{const root=await temp(),s=new RunService(root,{sourceFactory:()=>new PatenticsSource({key:'mock',store:new RunStore(root),limiter:{reserve:async()=>{}},fetchImpl:async()=>new Response('<Result><Total>40</Total><PatentList><Patent><p>CN1A</p><t>液氢</t></Patent></PatentList></Result>')})});const r=await s.start({kind:'search',topic:'液氢',strategy,analyze:false,page:2,previous_page_publications:['CN1A']});await terminal(s);const done=await s.store.get(r.run_id);assert.equal(done.stop_reason,'duplicate_page');assert.equal(done.api_calls,1);assert.equal(done.status,'partial');});

test('V03 explicit analysis runs even when automatic post-search analysis is disabled',async()=>{let calls=0;const s=new RunService(await temp(),{models:{generate:async(k,i)=>{calls++;return {output:output(i.records),metadata:{provider:'codex',model:'test'}};}}});const r=await s.start({kind:'analyze',topic:'液氢',strategy,task:task(),analyze:false});await terminal(s);const done=await s.store.get(r.run_id);assert.equal(calls,1);assert.equal(done.status,'completed');assert(done.task.model_analysis);});

test('V03 rule report questions cite representative passages without copying every fragment',()=>{const p=newProject('液氢');p.records=[record()];const sections=reportSections(p);const next=sections.find(s=>s.id==='next');const refs=[...next.text.matchAll(/\[(ev-[^\]]+)\]/g)];assert(refs.length>0);assert(refs.length<=projectTask(p).analysis.opportunities.length*p.records.length);});

test('V03 model errors retain classification without endpoint or secret text',()=>{assert.equal(classifyModelError({message:'Reconnecting after stream disconnected'}),'connection');assert.equal(classifyModelError({message:'HTTP 429 rate limit reached'}),'rate_limited');assert.equal(classifyModelError({message:'unknown private detail'}),'provider_error');});
