'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowDown,ArrowRight,ArrowUpRight,BookOpen,Check,ChevronRight,Database,FileText,FolderOpen,Layers,Plus,Search,Settings,SlidersHorizontal,Sparkles,Upload,Undo2,X} from 'lucide-react';
import {api,navigate,saveBlob,useRoute,useWorkspace} from './use-workspace';
import SearchComposer from './search-composer';
import EvidenceReader from './evidence-reader';
import {AnalysisView,ComparisonView,ReportWorkspace} from './research-views';
import {buildStrategy,createTask,parseImport} from '@/core/engine.mjs';
import {reportSections} from '@/core/project.mjs';
const statusLabels:Record<string,string>={queued:'准备中',planning:'整理检索策略',retrieving:'获取专利资料',analyzing:'分析证据',cancelling:'正在取消',cancelled:'已取消',interrupted:'服务中断',completed:'已完成',partial:'部分完成',failed:'未完成'};
const activeStates=['queued','planning','retrieving','analyzing','cancelling'];
export default function Xlab(){
  const route=useRoute(),w=useWorkspace(route.projectId),p=w.project;
  const [projects,setProjects]=useState<any[]>([]),[status,setStatus]=useState<any>(null),[run,setRun]=useState<any>(null),[topic,setTopic]=useState(''),[goal,setGoal]=useState('了解技术路线'),[creating,setCreating]=useState(false),[globalError,setGlobalError]=useState(''),[connectionError,setConnectionError]=useState('');
  const [filter,setFilter]=useState(''),[showFilters,setShowFilters]=useState(false),[keepFilter,setKeepFilter]=useState('all'),[applicant,setApplicant]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[roundFilter,setRoundFilter]=useState(''),[coverage,setCoverage]=useState('all'),[sort,setSort]=useState('platform'),[checked,setChecked]=useState<string[]>([]),[limit,setLimit]=useState(60);
  const file=useRef<HTMLInputElement>(null),lastTerminal=useRef('');
  useEffect(()=>{let stopped=false;async function poll(){try{const [s,items]=await Promise.all([api('/api/status'),api('/api/projects')]);if(stopped)return;setConnectionError('');setStatus(s);setProjects(items);const id=s.active_run||(run?.input.project_id===route.projectId?run.run_id:null);if(id){const r=await api('/api/runs/'+id);if(stopped)return;setRun(r);if(!activeStates.includes(r.status)&&!s.active_run&&lastTerminal.current!==r.run_id){lastTerminal.current=r.run_id;await w.refresh();}}}catch(e:any){if(!stopped)setConnectionError('本机服务暂时断开，正在重新连接。已打开的资料仍可阅读。');}}poll();const timer=setInterval(poll,1800);return()=>{stopped=true;clearInterval(timer);};},[route.projectId,run?.run_id,w.refresh]);
  useEffect(()=>{setFilter('');setChecked([]);setRoundFilter('');setLimit(60);},[route.projectId]);
  const busy=!!connectionError||!!status?.active_run||!!run&&activeStates.includes(run.status),ownRun=run?.input.project_id===p?.project_id?run:p?.last_run;
  async function go(id='',view='records',record='',evidence=''){try{await w.flush();navigate(id,view,record,evidence);}catch(e:any){w.setError(e.message);}}
  async function create(){setCreating(true);try{await w.flush();const next=await api('/api/projects','POST',{topic:topic.trim(),goal});setTopic('');navigate(next.project_id);}catch(e:any){setGlobalError(e.message);}finally{setCreating(false);}}
  async function start(kind:string,extra:any={}){try{const saved=await w.flush();const r=await api('/api/runs','POST',{project_id:saved.project_id,kind,idempotency_key:crypto.randomUUID(),...extra});setRun(r);setStatus((s:any)=>({...s,active_run:r.run_id}));setGlobalError('');}catch(e:any){w.setError(e.message);}}
  async function importFile(f:File){try{await w.flush();let next:any;if(f.name.toLowerCase().endsWith('.zip')){const r=await fetch('/api/projects/import',{method:'POST',headers:{'Content-Type':'application/zip'},body:f});next=await r.json();if(!r.ok)throw Error(next.error?.message||'归档导入失败');}else{const raw=await f.text();let parsed;try{parsed=JSON.parse(raw);}catch{}if(parsed?.schema||parsed?.schema_version===3)next=await api('/api/projects/import','POST',parsed);else{const name=f.name.replace(/\.[^.]+$/,''),dataset=parseImport(raw,f.name),strategy=buildStrategy(name),task=createTask(name,dataset,strategy);task.records=dataset.records;next=await api('/api/projects/import','POST',{schema:2,topic:name,strategy,dataset,task});}}navigate(next.project_id);}catch(e:any){setGlobalError(e.message);}finally{if(file.current)file.current.value='';}}
  async function archive(){try{await w.flush();const r=await fetch('/api/projects/'+p.project_id+'/archive');if(!r.ok){const e:any=await r.json();throw Error(e.error?.message);}saveBlob(await r.blob(),'XLAB-'+p.title+'.zip');}catch(e:any){w.setError(e.message);}}
  function evidence(id:string){id=p.evidence_aliases?.[id]||id;const r=p.records.find((r:any)=>r.evidence.some((e:any)=>e.evidence_id===id));if(r)go(p.project_id,'records',r.record_id,id);}
  function quote(e:any){w.update((n:any)=>{if(!n.report_draft.sections.length)n.report_draft.sections=reportSections(n);const s=n.report_draft.sections.find((s:any)=>s.id==='findings')||n.report_draft.sections[0];s.text+=`\n原文摘录：${e.text}\n[${e.evidence_id}]`;});}
  const records=p?p.records.filter((r:any)=>{const text=[r.publication_number,r.title,...r.applicants].join(' ').toLowerCase();return (!filter||text.includes(filter.toLowerCase()))&&(!applicant||r.applicants.join(' ').includes(applicant))&&(keepFilter==='all'||(keepFilter==='kept'?!p.excluded.includes(r.record_id):p.excluded.includes(r.record_id)))&&(!from||r.publication_date&&r.publication_date>=from)&&(!to||r.publication_date&&r.publication_date<=to)&&(coverage==='all'||coverage==='full'&&r.claims&&r.description||coverage==='missing'&&(!r.claims||!r.description))&&(!roundFilter||p.rounds.find((x:any)=>x.run_id===roundFilter)?.record_ids.includes(r.record_id));}):[];
  if(sort==='newest')records.sort((a:any,b:any)=>(b.publication_date||'').localeCompare(a.publication_date||''));if(sort==='oldest')records.sort((a:any,b:any)=>(a.publication_date||'').localeCompare(b.publication_date||''));
  const selected=p?.records.find((r:any)=>r.record_id===route.recordId),candidateRecords=p?.candidates.filter((c:any)=>!p.records.some((r:any)=>r.record_id===c.record_id))||[],latestRound=p?.rounds.at(-1);
  return <div className={'xlab '+(route.view==='home'?'is-home':'')}><input ref={file} type="file" accept=".zip,.json,.csv" className="hidden" aria-label="导入资料或项目备份" onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/>
  <aside className="app-sidebar no-print"><button className="brand" aria-label="XLAB 项目首页" onClick={()=>go()}><span className="brand-word">X<span>L</span>AB<span className="brand-dot">·</span></span><span className="brand-caption">专利研习 / RESEARCH LAB</span></button><button className="new-project" onClick={()=>go()}><Plus size={18}/>新建研究项目</button><nav aria-label="主要导航"><button className={route.view==='home'?'active':''} onClick={()=>go()}><FolderOpen size={19}/>我的项目</button>{p&&[['records','检索与阅读',Search],['analysis','分析与复核',Sparkles],['compare','技术比较',Layers],['report','研究报告',FileText]].map(([key,label,Icon]:any)=><button key={key} className={route.view===key?'active':''} onClick={()=>go(p.project_id,key)}><Icon size={19}/>{label}</button>)}</nav><div className="sidebar-projects"><span className="eyebrow">最近研究</span>{projects.slice(0,5).map(item=><button key={item.project_id} disabled={item.damaged} className={route.projectId===item.project_id?'current':''} onClick={()=>go(item.project_id)}><span className="project-dot"/>{item.title}</button>)}</div><footer><button onClick={async()=>{try{await w.flush();location.hash='/settings';}catch(e:any){w.setError(e.message);}}}><Settings size={18}/>连接与设置</button><div className="local-status"><span className={status&&!connectionError?'online-dot':'offline-dot'}/>{status&&!connectionError?'本机服务已连接':'正在连接本机服务'}<span>0.3.0</span></div></footer></aside>
  <main className="app-main"><header className="app-topbar no-print"><div className="breadcrumb"><button onClick={()=>go()}>我的项目</button>{p&&<><ChevronRight size={14}/><span>{p.title}</span></>}{route.view==='settings'&&<span>连接与设置</span>}</div><div className="actions"><button aria-label="连接与设置" onClick={async()=>{try{await w.flush();location.hash='/settings';}catch(e:any){w.setError(e.message);}}}><Settings size={17}/></button><span className="save-status">{p?w.saveState:'LOCAL WORKSPACE'}</span>{p&&<><button onClick={w.undo} title="撤销上一步" aria-label="撤销上一步"><Undo2 size={17}/></button><button onClick={archive}><ArrowDown size={17}/><span>项目备份</span></button></>}<button onClick={()=>file.current?.click()}><Upload size={17}/><span>导入</span></button></div></header>
  {connectionError&&<div className="notice warning no-print" role="status">{connectionError}</div>}
  {(globalError||w.error)&&<div className="notice error no-print" role="alert"><span>{w.error||globalError}</span><button aria-label="关闭提示" onClick={()=>{w.setError('');setGlobalError('');}}><X size={17}/></button></div>}
  {w.conflict&&<div className="notice warning no-print"><span>项目在其他页面已有更新。本页草稿仍保留，请选择处理方式。</span><button onClick={w.saveCopy}>将本页另存为项目</button><button onClick={w.loadLatest}>载入最新版本</button></div>}
  {route.view==='home'?<section className="project-home"><div className="home-heading"><div><span className="eyebrow">YOUR NEXT RESEARCH STARTS HERE</span><h1>从一个问题，<br/>走近技术的<span>原理。</span></h1><p>检索专利，读懂证据，形成研究判断。</p></div><div className="research-orbit" aria-hidden="true"><i/><i/><i/><span className="orbit-label one">01 / SEARCH</span><span className="orbit-label two">02 / EVIDENCE</span><span className="orbit-center">X<span>L</span></span><span className="orbit-label three">03 / INSIGHT</span></div></div><form className="home-search" onSubmit={e=>{e.preventDefault();create();}}><label htmlFor="research-question">你想研究什么？</label><textarea id="research-question" rows={2} maxLength={500} placeholder="例如：液氢储罐通过哪些结构控制压力？" value={topic} onChange={e=>setTopic(e.target.value)}/><div className="home-search-footer"><select aria-label="研究目的" value={goal} onChange={e=>setGoal(e.target.value)}><option>了解技术路线</option><option>比较结构方案</option><option>寻找进一步检索方向</option></select><button className="primary" disabled={!topic.trim()||creating}>开始研究 <ArrowUpRight size={19}/></button></div></form><div className="topic-examples"><span>试一个方向</span>{['液氢储罐压力调节','动力电池液冷结构','复合材料拉挤成型'].map(t=><button key={t} onClick={()=>setTopic(t)}>{t}<ArrowUpRight size={13}/></button>)}</div>{!status?.credentials?.patentics?.configured&&<div className="setup-hint"><Database size={19}/><span>首次使用？先连接你的专利数据源和分析服务。</span><button onClick={()=>location.hash='/settings'}>连接设置 <ArrowRight size={16}/></button></div>}<div className="recent-heading"><h2>继续你的研究 <span>{projects.length.toString().padStart(2,'0')}</span></h2><span className="small">资料保存在当前电脑</span></div><div className="project-grid">{projects.map((item,i)=><button key={item.project_id} className="project-card" disabled={item.damaged} onClick={()=>go(item.project_id)}><div className="project-card-top"><span>PROJECT / {(i+1).toString().padStart(2,'0')}</span><ArrowUpRight size={19}/></div><h3>{item.title}</h3><p>{item.goal||'专利资料研究'}</p><footer><span>{item.records||0} 篇资料 · {item.rounds||0} 轮检索</span><span>{item.updated_at?new Date(item.updated_at).toLocaleDateString():''}</span></footer></button>)}{!projects.length&&<div className="home-empty"><FolderOpen size={25}/><p>第一份研究，从上面的问题开始。</p><button onClick={()=>file.current?.click()}>或导入已有资料 ↗</button></div>}</div></section>:route.view==='settings'?<SettingsView status={status} onSaved={()=>api('/api/status').then(setStatus)} onError={setGlobalError}/>:!p?<div className="empty-state"><span className="loading-dot"/><h2>正在恢复研究项目…</h2></div>:<><div className="workspace-heading no-print"><div><span className="eyebrow">{p.goal}</span><h1>{p.title}</h1></div><span className="badge">{p.records.length} 篇已存资料 · {p.rounds.length} 轮检索</span></div>
  {ownRun&&<div className={'run-strip no-print '+(ownRun.status==='failed'?'warning':'')} role="status"><span className={activeStates.includes(ownRun.status)?'loading-dot':'status-dot'}/><strong>{statusLabels[ownRun.status]}</strong><span>{ownRun.acquired?.length||ownRun.task?.records.length||ownRun.detail_count||0} 篇详情 · 数据请求 {ownRun.api_calls}/20{ownRun.analysis_batches?` · 分析 ${ownRun.analysis_batches.filter((b:any)=>b.status==='completed').length}/${ownRun.analysis_batches.length} 批`:''}</span>{activeStates.includes(ownRun.status)?<button onClick={()=>api('/api/runs/'+ownRun.run_id+'/cancel','POST',{}).then(setRun).catch((e:any)=>w.setError(e.message))}>取消</button>:['failed','partial','cancelled','interrupted'].includes(ownRun.status)&&<button disabled={busy} onClick={()=>api('/api/runs/'+ownRun.run_id+'/retry','POST',{}).then(setRun).catch((e:any)=>w.setError(e.message))}>重试未完成部分</button>}{ownRun.error&&<span className="run-error">{ownRun.error.message}</span>}<details><summary>详情</summary><div>{ownRun.warnings?.map((x:any,i:number)=><p key={i}>{x.message}</p>)}<p>停止原因：{ownRun.stop_reason||'尚未停止'}</p></div></details></div>}
  {p.source_conflicts.some((c:any)=>c.status==='pending')&&<div className="notice warning">不同轮次取得了同一公开号的不同内容。当前沿用旧版本。{p.source_conflicts.filter((c:any)=>c.status==='pending').map((c:any)=><div key={c.conflict_id}>{c.record_id}<button onClick={async()=>{try{const saved=await w.flush();w.apply(await api('/api/projects/'+p.project_id,'PUT',{revision:saved.revision,resolve_conflict:{id:c.conflict_id,use:'incoming'}}));}catch(e:any){w.setError(e.message);}}}>改用新来源版本</button><button onClick={async()=>{const saved=await w.flush();w.apply(await api('/api/projects/'+p.project_id,'PUT',{revision:saved.revision,resolve_conflict:{id:c.conflict_id,use:'previous'}}));}}>保留旧来源版本</button></div>)}</div>}
  {route.view==='records'?<><SearchComposer project={p} update={w.update} run={start} busy={busy}/><div className={'reading-workspace '+(selected?'has-selection':'')}><section className="results-panel"><div className="result-count"><h2>研究资料 <span>{p.records.length}</span></h2><button aria-label="筛选资料" aria-expanded={showFilters} onClick={()=>setShowFilters(!showFilters)}><SlidersHorizontal size={17}/></button></div><label className="result-search"><Search size={16}/><input placeholder="标题、公开号、申请人" aria-label="搜索项目内资料" value={filter} onChange={e=>setFilter(e.target.value)}/></label>{showFilters&&<div className="result-filters"><label>保留状态<select value={keepFilter} onChange={e=>setKeepFilter(e.target.value)}><option value="all">全部资料</option><option value="kept">已保留</option><option value="excluded">已排除</option></select></label><label>完整程度<select value={coverage} onChange={e=>setCoverage(e.target.value)}><option value="all">全部</option><option value="full">含权利要求和说明书</option><option value="missing">有字段缺失</option></select></label><label>申请人<input value={applicant} onChange={e=>setApplicant(e.target.value)}/></label><label>检索轮次<select value={roundFilter} onChange={e=>setRoundFilter(e.target.value)}><option value="">全部轮次</option>{p.rounds.map((r:any)=><option key={r.run_id} value={r.run_id}>第 {r.sequence} 轮</option>)}</select></label><div className="dates"><label>起始日期<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>截止日期<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><label>排序<select value={sort} onChange={e=>setSort(e.target.value)}><option value="platform">采集顺序</option><option value="newest">公开日期从新到旧</option><option value="oldest">公开日期从旧到新</option></select></label></div>}
  <div className="result-summary"><span>{records.length} 条匹配 · {p.records.length-p.excluded.length} 条保留</span><button className="text-link" onClick={()=>setChecked(checked.length?[]:records.slice(0,20).map((r:any)=>r.record_id))}>{checked.length?'取消选择':'选择前20篇'}</button></div>{checked.length>0&&<div className="batch-toolbar"><span>已选 {checked.length}</span><button disabled={busy} onClick={()=>start('analyze',{record_ids:checked})}>分析</button><button onClick={()=>w.update((n:any)=>{n.excluded=[...new Set([...n.excluded,...checked])];})}>排除</button><button disabled={checked.length>4} onClick={()=>{w.update((n:any)=>{n.comparison.record_ids=checked;});go(p.project_id,'compare');}}>比较</button></div>}
  <div className="results-scroll">{records.slice(0,limit).map((r:any,i:number)=><article className={'result-card '+(route.recordId===r.record_id?'active ':'')+(p.excluded.includes(r.record_id)?'excluded':'')} key={r.record_id}><div className="result-top"><label className="check" title="选择此记录"><input aria-label={'选择 '+r.publication_number} type="checkbox" checked={checked.includes(r.record_id)} onChange={e=>setChecked(e.target.checked?[...checked,r.record_id]:checked.filter(id=>id!==r.record_id))}/><span>{String(i+1).padStart(2,'0')}</span></label><span className="publication">{r.publication_number}</span><span>{r.publication_date?.slice(0,4)||'日期缺失'}</span></div><button className="result-open" onClick={()=>go(p.project_id,'records',r.record_id)}><h3>{r.title}</h3><p>{r.abstract_excerpt?.slice(0,110)||r.evidence[0]?.text.slice(0,110)||'暂未取得摘要'}</p></button><footer><span>{r.applicants[0]||'申请人未提供'}</span><span className={'coverage '+(r.claims&&r.description?'good':'')}>{r.claims&&r.description?'全文证据':'部分证据'}</span></footer></article>)}{records.length>limit&&<button className="load-more" onClick={()=>setLimit(limit+60)}>显示更多已存资料</button>}{!records.length&&<div className="list-empty"><Search size={26}/><h3>{p.records.length?'没有匹配资料':'开始第一轮检索'}</h3><p>{p.records.length?'试着放宽筛选条件。':'编辑上方检索策略，或直接检索专利。'}</p></div>}
  {candidateRecords.length>0&&<details className="candidates"><summary>待补全文候选 · {candidateRecords.length}</summary>{candidateRecords.map((c:any)=><div key={c.record_id}><strong>{c.title}</strong><span className="publication">{c.publication_number}</span><button disabled={busy} onClick={()=>start('collect',{record_ids:[c.record_id]})}>补充详情</button></div>)}</details>}
  </div><footer className="results-bottom"><span className="small muted">平台命中 {latestRound?.source_total??'—'} · 已存候选 {p.candidates.length}</span><button disabled={busy||!latestRound?.source_pages||(latestRound.actual_query?.pn||1)>=latestRound.source_pages} onClick={()=>start('search',{page:(latestRound.actual_query?.pn||1)+1})}>下一页 <ArrowRight size={16}/></button></footer></section><EvidenceReader record={selected} project={p} update={w.update} records={records} onRecord={(id:string)=>go(p.project_id,'records',id)} onEvidence={evidence} focusEvidence={route.evidenceId} onQuote={quote}/></div></>:route.view==='analysis'?<AnalysisView project={p} update={w.update} onEvidence={evidence} onAnalyze={()=>start('analyze',{record_ids:p.records.filter((r:any)=>!p.excluded.includes(r.record_id)).map((r:any)=>r.record_id)})} busy={busy}/>:route.view==='compare'?<ComparisonView project={p} update={w.update} onEvidence={evidence}/>:<ReportWorkspace workspace={w} onEvidence={evidence}/>}</>}
  </main></div>;
}
function SettingsView({status,onSaved,onError}:any){
  const [provider,setProvider]=useState('patentics'),[key,setKey]=useState(''),[saved,setSaved]=useState(''),[saving,setSaving]=useState(false);
  async function save(){setSaving(true);try{await api('/api/settings','POST',{provider,key});setKey('');setSaved('凭据已加密保存到当前 Windows 用户。实际可用性以成功调用为准。');await onSaved();}catch(e:any){onError(e.message);}finally{setSaving(false);}}
  return <section className="settings-page"><span className="eyebrow">CONNECTIONS</span><h1>连接你的研究工具</h1><p className="muted">专利数据源负责取资料，模型负责整理证据。两者独立配置。</p><div className="connection-grid"><article><Database size={24}/><h2>Patentics</h2><span className="badge">{status?.source?.state==='verified'?'最近取数成功':status?.credentials?.patentics?.configured?'已配置':'待配置'}</span><p>中国专利库 cnapp</p>{status?.source?.checked_at&&<p className="small muted">核验时间：{new Date(status.source.checked_at).toLocaleString()}</p>}<p className="small muted">按指定网关获取题录、摘要、权利要求和说明书。当前网关使用 HTTP；本机凭据加密存储不代表传输已加密。</p></article><article><Sparkles size={24}/><h2>Codex</h2><span className="badge">{status?.providers?.codex?.state==='verified'?'最近调用成功':status?.providers?.codex?.state==='ready'?'已安装，待调用验证':status?.providers?.codex?.state==='failed'?'最近调用未完成':'待核验'}</span><p>{status?.providers?.codex?.model||'gpt-6-astra'}</p>{status?.providers?.codex?.error&&<p className="small muted">{status.providers.codex.error}</p>}<p className="small muted">使用本机桌面 Codex 登录。{status?.providers?.codex?.version||'未识别版本'}。{status?.providers?.codex?.checked_at&&'核验时间：'+new Date(status.providers.codex.checked_at).toLocaleString()}</p></article><article><Layers size={24}/><h2>智谱 GLM</h2><span className="badge">{status?.providers?.glm?.state==='verified'?'最近调用成功':status?.credentials?.glm?.configured?'已配置，尚待成功调用':'可选服务'}</span><p>glm-4.7-flash</p><p className="small muted">仅按项目中明确选择的服务运行。失败保留资料，不自动切换。</p></article></div><section className="credential-form"><h2>配置本机凭据</h2><label>服务<select value={provider} onChange={e=>setProvider(e.target.value)}><option value="patentics">Patentics 专利数据源</option><option value="glm">智谱模型</option></select></label><label>API 凭据<input autoComplete="off" type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="仅在当前电脑加密保存"/></label><button className="primary" disabled={!key.trim()||saving} onClick={save}><Check size={16}/>加密保存</button><p className="small muted">{saved||'凭据不会进入项目备份、报告或源码包。每位成员使用自己的服务授权。'}</p></section><section className="panel"><h2>首次使用</h2><ol><li>配置 Patentics 数据源。</li><li>在本机 Codex 桌面应用中登录自己的账号。</li><li>创建研究项目，执行一次检索和分析，核验真实连接状态。</li></ol><p className="small muted">也可以导入已有 JSON、CSV 或项目 ZIP，先开展资料阅读。</p></section></section>;
}
