'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ChevronLeft,ChevronRight,Bookmark,Pin,FileText,Quote,Search,Download} from 'lucide-react';
const fieldName:Record<string,string>={abstract_excerpt:'摘要',claims:'权利要求',description:'说明书'};
export function CitationText({text,onEvidence}:any){return <>{String(text||'').split(/(\[ev-[^\]]+\])/g).map((part,i)=>part.startsWith('[ev-')?<button key={i} className="citation" data-citation={part} aria-label={part} onClick={()=>onEvidence(part.slice(1,-1))}>[{part.slice(4,24)}…]</button>:<span key={i}>{part}</span>)}</>;}
export default function EvidenceReader({record:r,project:p,update,onRecord,onEvidence,records,focusEvidence,onQuote}:any){
  const [field,setField]=useState('evidence'),[query,setQuery]=useState('');const scroller=useRef<HTMLDivElement>(null),positions=useRef<Record<string,number>>({});
  useEffect(()=>{if(scroller.current)scroller.current.scrollTop=positions.current[r?.record_id]||0;setQuery('');},[r?.record_id]);
  useEffect(()=>{if(focusEvidence){setField('evidence');const t=setTimeout(()=>document.getElementById(focusEvidence)?.scrollIntoView({block:'center',behavior:'smooth'}),80);return()=>clearTimeout(t);}},[focusEvidence,r?.record_id]);
  if(!r)return <div className="reader-empty"><BookGlyph/><span className="eyebrow">EVIDENCE READER</span><h2>从一篇专利开始阅读</h2><p>选择左侧记录，查看原文、标记证据，<br/>把你的判断写进研究笔记。</p><div className="reader-steps"><span>01 阅读原文</span><span>02 比较结构</span><span>03 引用到报告</span></div></div>;
  const index=records.findIndex((x:any)=>x.record_id===r.record_id),excluded=p.excluded.includes(r.record_id),evidence=r.evidence.filter((e:any)=>!query||[e.text,e.locator,e.evidence_id].join(' ').toLowerCase().includes(query.toLowerCase()));
  return <article className="reader"><header className="reader-controls"><button className="mobile-back" onClick={()=>onRecord('')}><ArrowLeft size={17}/>结果列表</button><div className="actions"><button title="上一篇" aria-label="上一篇" disabled={index<=0} onClick={()=>onRecord(records[index-1].record_id)}><ChevronLeft size={18}/></button><span className="small">{index+1} / {records.length}</span><button title="下一篇" aria-label="下一篇" disabled={index<0||index>=records.length-1} onClick={()=>onRecord(records[index+1].record_id)}><ChevronRight size={18}/></button></div><button className={excluded?'':'selected'} onClick={()=>update((n:any)=>{n.excluded=excluded?n.excluded.filter((id:string)=>id!==r.record_id):[...n.excluded,r.record_id];})}><Bookmark size={16}/>{excluded?'恢复保留':'已保留'}</button></header>
  <div className="reader-scroll" ref={scroller} onScroll={e=>{positions.current[r.record_id]=e.currentTarget.scrollTop;}}><div className="reader-title"><span className="publication">{r.publication_number}</span><span className="badge">{r.data_mode==='live'?'本机采集':'已存资料'}</span><h2>{r.title}</h2><p>{r.applicants.join(' · ')||'申请人未提供'}<br/><span className="small">公开日期 {r.publication_date||'未提供'}</span></p></div>
  <div className="reader-tabs" role="tablist" aria-label="专利正文">{[['evidence','证据片段'],['abstract_excerpt','摘要'],['claims','权利要求'],['description','说明书']].map(([key,label])=><button key={key} role="tab" aria-selected={field===key} onClick={()=>setField(key)}>{label}</button>)}</div>
  <label className="reader-search"><Search size={15}/><input aria-label="查找原文或证据编号" placeholder="查找原文或证据编号" value={query} onChange={e=>{setQuery(e.target.value);}}/></label>
  {field==='evidence'?<div className="evidence-list">{evidence.length?evidence.map((e:any)=><section key={e.evidence_id} id={e.evidence_id} className={'evidence-block '+(focusEvidence===e.evidence_id?'focused':'')}><div className="evidence-label"><span>{fieldName[e.field]||e.field} · {e.locator}</span><button aria-label={p.pins.includes(e.evidence_id)?'取消钉选证据':'钉选证据'} className={p.pins.includes(e.evidence_id)?'selected':''} onClick={()=>update((n:any)=>{n.pins=n.pins.includes(e.evidence_id)?n.pins.filter((id:string)=>id!==e.evidence_id):[...n.pins,e.evidence_id];})}><Pin size={15}/></button></div><blockquote>{e.text}</blockquote><div className="actions"><button onClick={()=>update((n:any)=>{n.notes[r.record_id]=(n.notes[r.record_id]||'')+`\n${e.text}\n[${e.evidence_id}]`;})}><Quote size={14}/>引用到笔记</button><button onClick={()=>onQuote(e)}><FileText size={14}/>引用到报告</button></div><details className="source-details"><summary>来源与定位</summary><p>{e.evidence_id}</p><p>SHA-256：{e.source_asset_id||'旧备份未包含原始来源'}</p><p>原文位置：{e.source_start??'未提供'}—{e.source_end??'未提供'}</p></details></section>):<p className="empty-inline">没有匹配片段，可切换全文继续查找。</p>}</div>:<div className="fulltext"><FullText text={r[field]||'网关未提供这一部分正文。'} query={query}/></div>}
  <section className="reading-note"><label>这篇专利与你的研究有什么关系？<textarea rows={4} placeholder="记录结构特征、适用条件和待核验之处…" value={p.notes[r.record_id]||''} onChange={e=>update((n:any)=>{n.notes[r.record_id]=e.target.value;})}/></label></section><footer className="reader-footer">{r.source_metadata?.raw_sha256?<a className="button" href={'/api/source-assets/'+r.source_metadata.raw_sha256} download><Download size={15}/>原始 XML</a>:<span className="small muted">旧备份未包含原始 XML</span>}<p className="small muted">原文记载需结合适用条件阅读。采集时间：{r.retrieved_at?new Date(r.retrieved_at).toLocaleString():'未提供'}</p></footer></div></article>;
}
function BookGlyph(){return <div className="book-glyph"><div/><div/><span>文献 / 证据 / 思考</span></div>;}

function FullText({text,query}:any){const value=String(text),needle=String(query).trim();if(!needle)return <>{value}</>;const parts=[];let from=0,index=0,count=0;while((index=value.toLowerCase().indexOf(needle.toLowerCase(),from))>=0){parts.push(<span key={from}>{value.slice(from,index)}</span>,<mark key={"hit"+index}>{value.slice(index,index+needle.length)}</mark>);from=index+needle.length;count++;}parts.push(<span key="tail">{value.slice(from)}</span>);return <><p className="small muted" role="status">本节匹配 {count} 处</p>{parts}</>;}
