'use client';
import {useRef,useState} from 'react';
import {ArrowDown,ArrowUp,Check,Download,FileText,Plus,Printer,Sparkles,X} from 'lucide-react';
import {projectTask,reportSections} from '@/core/project.mjs';
import {modelState,effectiveAnalysis} from '@/core/model-analysis.mjs';
import {markdownToDocx} from '@/core/docx.mjs';
import {api,downloadFile} from './use-workspace';
import {CitationText} from './evidence-reader';
export function AnalysisView({project:p,update,onEvidence,onAnalyze,busy}:any){
  const task=projectTask(p),state=modelState(task),analysis=effectiveAnalysis(task);
  return <section className="research-page"><header className="section-heading"><div><span className="eyebrow">RESEARCH INSIGHTS</span><h2>让判断回到证据</h2><p>从技术路线出发，逐项核对原文、适用范围和遗漏。</p></div><button className="primary" disabled={busy} onClick={onAnalyze}><Sparkles size={16}/>分析保留的资料</button></header>
  {state==='stale'&&<div className="notice warning">策略或保留资料已改变，上一版分析已过期。重新分析前，当前显示规则整理。</div>}
  {state==='none'&&<div className="notice">尚未生成 AI 分析。当前路线仅为词项规则整理。</div>}
  <div className="route-cards">{analysis.groups.map((g:any,i:number)=><article key={g.group_id}><span className="route-number">0{i+1}</span><h3>{g.label}</h3><p>{g.reason}</p><div className="actions wrap">{g.evidence_ids.slice(0,4).map((id:string)=><button className="text-link" key={id} onClick={()=>onEvidence(id)}>查看依据 ↗</button>)}</div></article>)}</div>
  <h3 className="subheading">发现与待核验问题 <span className="badge">{state==='current'?'本次模型分析':state==='replay'?'历史结果回放':'规则整理'}</span></h3>
  {[...analysis.claims,...analysis.opportunities].map((c:any)=><article className="finding" key={c.claim_id}><div className="finding-head">{c.quotes?.length>0&&<span className="badge">引文逐字匹配</span>}<span className="badge">{c.type==='source_fact'?'原文摘录':c.type==='research_question'?'研究问题':'AI 推断'}</span><span className="small muted">{p.reviews[c.claim_id]?.state==='adopted'?'人工采纳':p.reviews[c.claim_id]?.state==='rejected'?'已驳回':'待人工复核'}</span></div><textarea aria-label="研究判断" value={p.reviews[c.claim_id]?.text??c.text} rows={3} onChange={e=>update((n:any)=>{n.reviews[c.claim_id]={...n.reviews[c.claim_id],text:e.target.value,state:'pending'};})}/><p className="small muted">范围：{c.scope}　限制：{c.limitations}</p><div className="actions wrap">{c.evidence_ids.map((id:string)=><button className="text-link" key={id} onClick={()=>onEvidence(id)}>核对引用 ↗</button>)}<button onClick={()=>update((n:any)=>{n.reviews[c.claim_id]={...n.reviews[c.claim_id],state:'adopted',at:new Date().toISOString()};})}><Check size={16}/>采纳</button><button onClick={()=>update((n:any)=>{n.reviews[c.claim_id]={...n.reviews[c.claim_id],state:'rejected',at:new Date().toISOString()};})}><X size={16}/>驳回</button></div></article>)}
  {p.analyses.length>0&&<details className="panel"><summary>实际分析范围与版本记录</summary>{p.analyses.slice().reverse().map((a:any)=><div key={a.run_id}><p>{a.model_analysis.model} · {a.model_analysis.generated_at} · {a.model_calls} 次调用</p>{a.model_analysis.evidence_selection?.map((b:any,i:number)=><p className="small muted" key={i}>第 {i+1} 批：{b.record_ids.length} 篇、{b.evidence_ids.length} 个片段、{b.characters} 字符；另有 {b.omitted} 个片段未发送。</p>)}</div>)}</details>}
  </section>;
}
export function ComparisonView({project:p,update,onEvidence}:any){
  const [selectedDimension,setDimension]=useState('技术问题'),[newDimension,setNewDimension]=useState('');const records=p.records.filter((r:any)=>p.comparison.record_ids.includes(r.record_id)),dims=p.comparison.dimensions,dimension=dims.includes(selectedDimension)?selectedDimension:dims[0];
  function toggle(id:string){update((n:any)=>{n.comparison.record_ids=n.comparison.record_ids.includes(id)?n.comparison.record_ids.filter((x:string)=>x!==id):n.comparison.record_ids.length<4?[...n.comparison.record_ids,id]:n.comparison.record_ids;});}
  function excerpt(r:any,d:string){const field=d==='技术问题'?'abstract_excerpt':d==='核心结构'?'claims':'description',e=r.evidence.find((e:any)=>e.field===field);if(e)update((n:any)=>{n.comparison.cells[r.record_id+'|'+d]=`原文摘录：${e.text}\n[${e.evidence_id}]`;});}
  return <section className="research-page"><header className="section-heading"><div><span className="eyebrow">SIDE BY SIDE</span><h2>比较技术特征</h2><p>选择 2—4 篇专利，从结构、机制与应用条件展开比较。</p></div><span className="badge">已选 {records.length} / 4</span></header><details className="comparison-selection" open={records.length<2?true:undefined}><summary>调整比较资料 · 已选 {records.length} 篇</summary><div className="compare-picker">{p.records.map((r:any)=><label className="check" key={r.record_id}><input type="checkbox" checked={p.comparison.record_ids.includes(r.record_id)} disabled={records.length>=4&&!p.comparison.record_ids.includes(r.record_id)} onChange={()=>toggle(r.record_id)}/>{r.title}</label>)}</div></details>
  <div className="dimension-toolbar"><label>比较维度<select value={dims.includes(dimension)?dimension:dims[0]} onChange={e=>setDimension(e.target.value)}>{dims.map((d:string)=><option key={d}>{d}</option>)}</select></label><input aria-label="新增比较维度" placeholder="新增维度，如密封结构" value={newDimension} onChange={e=>setNewDimension(e.target.value)}/><button disabled={!newDimension.trim()||dims.includes(newDimension.trim())} onClick={()=>{update((n:any)=>n.comparison.dimensions.push(newDimension.trim()));setDimension(newDimension.trim());setNewDimension('');}}><Plus size={16}/>添加</button><button disabled={dims.length<=1} onClick={()=>{update((n:any)=>{n.comparison.dimensions=n.comparison.dimensions.filter((d:string)=>d!==dimension);});setDimension(dims.find((d:string)=>d!==dimension));}}>移除此维度</button></div>
  {records.length<2?<div className="empty-state"><h3>先选择两篇资料</h3><p>可以从同一技术问题出发，对照不同实现方式。</p></div>:<div className="compare-grid" style={{'--compare-count':records.length} as any}>{records.map((r:any)=><article className="compare-column" key={r.record_id}><span className="publication">{r.publication_number}</span><h3>{r.title}</h3><p className="small muted">{dimension}</p><textarea aria-label={r.publication_number+' '+dimension} rows={10} value={p.comparison.cells[r.record_id+'|'+dimension]||''} placeholder="未找到相关证据。插入原文引用，或注明“人工来源：具体出处”，再写下比较判断。" onChange={e=>update((n:any)=>{n.comparison.cells[r.record_id+'|'+dimension]=e.target.value;})}/><button onClick={()=>excerpt(r,dimension)}>插入相关字段原文</button><div className="citation-preview"><CitationText text={p.comparison.cells[r.record_id+'|'+dimension]||''} onEvidence={onEvidence}/></div></article>)}</div>}
  <p className="small muted">原文记载和人工比较分别注明。缺失资料不视为没有该特征，也不据此推算性能排名。</p></section>;
}
export function ReportWorkspace({workspace:w,onEvidence}:any){
  const p=w.project,[active,setActive]=useState('scope'),[view,setView]=useState('edit'),[historyId,setHistoryId]=useState(''),[message,setMessage]=useState('');
  const sections=p.report_draft.sections.length?p.report_draft.sections:reportSections(p),section=sections.find((s:any)=>s.id===active)||sections[0],history=historyId?p.reports.find((r:any)=>r.report_id===historyId):p.reports.at(-1);
  function edit(fn:(items:any[])=>void){w.update((n:any)=>{if(!n.report_draft.sections.length)n.report_draft.sections=reportSections(n);fn(n.report_draft.sections);});}
  const freezing=useRef<Promise<any>|null>(null),[freezingState,setFreezingState]=useState(false);
  function freeze():Promise<any>{if(freezing.current)return freezing.current;setFreezingState(true);freezing.current=(async()=>{const saved=await w.flush();const result=await api('/api/projects/'+p.project_id+'/reports','POST',{revision:saved.revision});w.acceptServer(result.project);setHistoryId(result.report.report_id);setMessage('已保存报告版本 '+result.report.version);return result.report;})().finally(()=>{freezing.current=null;setFreezingState(false);});return freezing.current;}
  async function exportAs(type:string){try{const report=view==='history'&&history?history:await freeze();if(type==='docx')await downloadFile('XLAB-'+report.report_id+'.docx',markdownToDocx(report.markdown),'application/vnd.openxmlformats-officedocument.wordprocessingml.document');else await downloadFile('XLAB-'+report.report_id+'.'+type,type==='json'?JSON.stringify(report,null,2):report.markdown,type==='json'?'application/json':'text/plain;charset=utf-8');setMessage('已提交下载，请在浏览器下载记录中查看');}catch(e:any){w.setError(e.message);}}
  async function rebuild(){try{await freeze();w.update((n:any)=>{n.report_draft.sections=reportSections(n);});setActive('scope');setView('edit');setMessage('旧草稿已保存为历史版本，已按当前资料与分析生成新草稿');}catch(e:any){w.setError(e.message);}}
  async function print(){try{if(view!=='history'||!history)await freeze();setView('history');setTimeout(()=>window.print(),250);}catch(e:any){w.setError(e.message);}}
  return <section className="report-workspace"><header className="section-heading no-print"><div><span className="eyebrow">RESEARCH REPORT</span><h2>把证据写成判断</h2><p>{message||'编辑保存为草稿，导出时冻结为独立报告版本。'}</p></div><div className="actions wrap"><button disabled={freezingState} onClick={()=>freeze().catch((e:any)=>w.setError(e.message))}><FileText size={16}/>保存版本</button><button disabled={freezingState} onClick={()=>exportAs('docx')}><Download size={16}/>Word</button><button disabled={freezingState} onClick={()=>exportAs('md')}>Markdown</button><button disabled={freezingState} onClick={()=>exportAs('json')}>JSON</button><button disabled={freezingState} onClick={print}><Printer size={16}/>打印 / PDF</button></div></header>
  {modelState(projectTask(p))==='stale'&&<div className="notice warning no-print">资料或策略已变化，原 AI 分析已过期。草稿保留原文字，请在导出前重新核对判断与引用。</div>}<div className="report-mode no-print"><button disabled={freezingState} onClick={rebuild}>按当前资料重建草稿</button><button className={view==='edit'?'selected':''} onClick={()=>setView('edit')}>编辑草稿</button><button disabled={!p.reports.length} className={view==='history'?'selected':''} onClick={()=>setView('history')}>历史报告 ({p.reports.length})</button>{view==='history'&&<select aria-label="报告版本" value={history?.report_id||''} onChange={e=>setHistoryId(e.target.value)}>{p.reports.map((r:any)=><option key={r.report_id} value={r.report_id}>版本 {r.version} · {new Date(r.created_at).toLocaleString()}</option>)}</select>}</div>
  {view==='edit'?<div className="report-columns"><nav className="chapter-nav" aria-label="报告章节">{sections.map((s:any,i:number)=><button key={s.id} className={s.id===section.id?'active':''} onClick={()=>setActive(s.id)}><span>0{i+1}</span>{s.title}</button>)}<button onClick={()=>{const id='section-'+Date.now();edit(items=>items.push({id,title:'补充研究判断',text:''}));setActive(id);}}><Plus size={15}/>增加章节</button></nav><div className="chapter-editor"><label>报告标题<input value={p.report_draft.title||p.title+'：专利研究报告'} onChange={e=>w.update((n:any)=>{n.report_draft.title=e.target.value;})}/></label><div className="chapter-title"><input aria-label="章节标题" value={section.title} onChange={e=>edit(items=>{items.find(s=>s.id===section.id).title=e.target.value;})}/><button aria-label="章节上移" disabled={sections.indexOf(section)===0} onClick={()=>edit(items=>{const i=items.findIndex(s=>s.id===section.id);[items[i-1],items[i]]=[items[i],items[i-1]];})}><ArrowUp size={17}/></button><button aria-label="章节下移" disabled={sections.indexOf(section)===sections.length-1} onClick={()=>edit(items=>{const i=items.findIndex(s=>s.id===section.id);[items[i+1],items[i]]=[items[i],items[i+1]];})}><ArrowDown size={17}/></button></div><textarea className="report-body" aria-label="章节正文" value={section.text} onChange={e=>edit(items=>{items.find(s=>s.id===section.id).text=e.target.value;})}/><div className="chapter-preview"><CitationText text={section.text} onEvidence={onEvidence}/></div></div><aside className="report-citations"><h3>可引用证据</h3><p className="small muted">点击“插入”后可继续编辑判断。</p>{p.records.filter((r:any)=>!p.excluded.includes(r.record_id)).flatMap((r:any)=>r.evidence.slice(0,3)).map((e:any)=><article key={e.evidence_id}><span className="small publication">{e.record_id.replace('pat-','')}</span><p>{e.text.slice(0,110)}…</p><div className="actions"><button onClick={()=>edit(items=>{items.find(s=>s.id===section.id).text+=`\n[${e.evidence_id}]`;} )}>插入</button><button onClick={()=>onEvidence(e.evidence_id)}>原文 ↗</button></div></article>)}</aside></div>:<article className="report-paper">{history?.markdown.split('\n').map((line:string,i:number)=>line.startsWith('# ')?<h1 key={i}>{line.slice(2)}</h1>:line.startsWith('## ')?<h2 key={i}>{line.slice(3)}</h2>:<p key={i}><CitationText text={line} onEvidence={onEvidence}/></p>)}</article>}
  </section>;
}
