'use client';
import {useEffect,useState} from 'react';
import {Search,SlidersHorizontal,Sparkles,ArrowUpRight,History} from 'lucide-react';
import {compileQuery} from '@/core/query.mjs';
export default function SearchComposer({project:p,update,run,busy}:any){
  const [open,setOpen]=useState(!p.records.length),[history,setHistory]=useState(false);const d=p.draft;useEffect(()=>{if(p.records.length)setOpen(false);},[p.records.length]);
  function strategy(key:string,value:any){update((n:any)=>{n.draft.strategy[key]=value;if(!n.draft.manual){try{n.draft.query=compileQuery(n.draft.strategy,n.title);}catch{n.draft.query='';}}});}
  return <section className="search-composer">
    <div className="composer-bar"><div><span className="eyebrow">研究范围</span><span className="scope-label">中国专利 · 标题与摘要 · {d.strategy.from||'不限起始日期'}</span></div><div className="actions"><button onClick={()=>setHistory(!history)}><History size={16}/>检索历史 <span className="count">{p.rounds.length}</span></button><button aria-expanded={open} onClick={()=>setOpen(!open)}><SlidersHorizontal size={16}/>{open?'收起策略':'编辑策略'}</button><button className="primary" disabled={busy} onClick={()=>run(d.auto_strategy&&!d.manual&&!p.rounds.length?'explore':'search')}><Search size={16}/>{p.rounds.length?'执行新一轮检索':'检索专利'}<ArrowUpRight size={16}/></button></div></div>
    {open&&<div className="composer-fields"><div className="field-grid"><label>技术对象与同义词<input value={d.strategy.object_terms.join('，')} onChange={e=>strategy('object_terms',e.target.value.split(/[，,]/).map(s=>s.trim()).filter(Boolean))}/></label><label>关注特征<input value={d.strategy.focus_terms.join('，')} onChange={e=>strategy('focus_terms',e.target.value.split(/[，,]/).map(s=>s.trim()).filter(Boolean))}/></label><label>排除词<input placeholder="可留空" value={d.strategy.exclude_terms.join('，')} onChange={e=>strategy('exclude_terms',e.target.value.split(/[，,]/).map(s=>s.trim()).filter(Boolean))}/></label><label>公开日期范围<div className="dates"><input aria-label="起始日期" type="date" value={d.strategy.from||''} onChange={e=>strategy('from',e.target.value||null)}/><input aria-label="截止日期" type="date" value={d.strategy.to||''} onChange={e=>strategy('to',e.target.value||null)}/></div></label></div>
    <label>实际检索式 <span className="badge">{d.manual?'手工接管':'随词项生成'}</span><textarea className="query-input" rows={3} value={d.query} onChange={e=>update((n:any)=>{n.draft.query=e.target.value;n.draft.manual=true;})}/></label>
    <div className="actions wrap"><label>分析服务<select value={d.provider} onChange={e=>update((n:any)=>{n.draft.provider=e.target.value;})}><option value="codex">Codex · gpt-6-astra</option><option value="glm">智谱 · 可选，需实测</option></select></label><label className="check"><input type="checkbox" checked={d.auto_strategy} onChange={e=>update((n:any)=>{n.draft.auto_strategy=e.target.checked;})}/>首次检索前由 AI 整理关键词</label><label className="check"><input type="checkbox" checked={d.analyze} onChange={e=>update((n:any)=>{n.draft.analyze=e.target.checked;})}/>取得资料后分析</label><button disabled={busy||d.manual} onClick={()=>run('strategy')}><Sparkles size={15}/>AI 辅助调整</button>{d.manual&&<button onClick={()=>update((n:any)=>{n.draft.manual=false;n.draft.query=compileQuery(n.draft.strategy,n.title);})}>恢复词项生成</button>}</div><p className="small muted">每轮查看 20 条候选，顺序取得最多 5 篇可用详情。手工检索式始终以这里的内容为准。</p></div>}
    {history&&<div className="query-history">{p.rounds.length?p.rounds.slice().reverse().map((r:any)=><article key={r.run_id}><div><strong>第 {r.sequence} 轮</strong><span className="small muted">{new Date(r.created_at).toLocaleString()} · 第 {r.actual_query?.pn||1} 页 · {r.record_ids?.length||0} 篇详情</span></div><code>{r.actual_query?.sq||'导入的历史资料'}</code><button onClick={()=>{update((n:any)=>{n.draft.strategy=r.strategy||n.draft.strategy;n.draft.query=r.actual_query?.sq||n.draft.query;n.draft.manual=true;});setOpen(true);}}>复用此检索式</button></article>):<p className="muted">执行第一轮检索后，在这里查看查询历史。</p>}</div>}
  </section>;
}
