/** Minimal dependency-free OPC/OOXML export. ZIP uses STORE to run in Node and browsers. */
const enc=new TextEncoder();
const xml=s=>String(s).replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function crc32(bytes){let crc=-1;for(const b of bytes){crc^=b;for(let j=0;j<8;j++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return (crc^-1)>>>0;}
function head(n){const a=new Uint8Array(n);return {a,v:new DataView(a.buffer)};}
export function zipFiles(files){let chunks=[],central=[],offset=0;for(const [name,value]of Object.entries(files)){const n=enc.encode(name),b=typeof value==='string'?enc.encode(value):value,c=crc32(b),l=head(30+n.length);l.v.setUint32(0,0x04034b50,true);l.v.setUint16(4,20,true);l.v.setUint16(6,0x800,true);l.v.setUint32(14,c,true);l.v.setUint32(18,b.length,true);l.v.setUint32(22,b.length,true);l.v.setUint16(26,n.length,true);l.a.set(n,30);chunks.push(l.a,b);const d=head(46+n.length);d.v.setUint32(0,0x02014b50,true);d.v.setUint16(4,20,true);d.v.setUint16(6,20,true);d.v.setUint16(8,0x800,true);d.v.setUint32(16,c,true);d.v.setUint32(20,b.length,true);d.v.setUint32(24,b.length,true);d.v.setUint16(28,n.length,true);d.v.setUint32(42,offset,true);d.a.set(n,46);central.push(d.a);offset+=l.a.length+b.length;}
 const cs=central.reduce((n,b)=>n+b.length,0),end=head(22);end.v.setUint32(0,0x06054b50,true);end.v.setUint16(8,central.length,true);end.v.setUint16(10,central.length,true);end.v.setUint32(12,cs,true);end.v.setUint32(16,offset,true);const all=[...chunks,...central,end.a],out=new Uint8Array(all.reduce((n,b)=>n+b.length,0));let i=0;for(const b of all){out.set(b,i);i+=b.length;}return out;}
export function markdownToDocx(markdown){
 let relations=[],bookmarks=new Map(),bookmarkSeq=1;
 for(const line of markdown.split('\n'))if(/^\[ev-/.test(line)){const id=line.match(/^\[([^\]]+)\]/)?.[1];if(id)bookmarks.set(id,`ev${bookmarkSeq++}`);}
 function runs(value){const parts=value.split(/(https?:\/\/[^\s。]+|\[ev-[^\]]+\])/g);return parts.map(part=>{if(/^https?:\/\//.test(part)){const id=`link${relations.length+1}`;relations.push({id,url:part});return `<w:hyperlink r:id="${id}"><w:r><w:rPr><w:color w:val="2563A0"/><w:u w:val="single"/></w:rPr><w:t>${xml(part)}</w:t></w:r></w:hyperlink>`;}const eid=part.match(/^\[(ev-[^\]]+)\]$/)?.[1];if(eid&&bookmarks.has(eid))return `<w:hyperlink w:anchor="${bookmarks.get(eid)}"><w:r><w:rPr><w:color w:val="2563A0"/></w:rPr><w:t>${xml(part)}</w:t></w:r></w:hyperlink>`;return `<w:r><w:t xml:space="preserve">${xml(part)}</w:t></w:r>`;}).join('');}
 const body=markdown.split('\n').filter(x=>x.trim()).map(line=>{let style='Normal',value=line;if(line.startsWith('# ')){style='Title';value=line.slice(2);}else if(line.startsWith('## ')){style='Heading1';value=line.slice(3);}else if(line.startsWith('### ')){style='Heading2';value=line.slice(4);}const id=line.match(/^\[(ev-[^\]]+)\]/)?.[1],b=id&&bookmarks.get(id);return `<w:p><w:pPr><w:pStyle w:val="${style}"/></w:pPr>${b?`<w:bookmarkStart w:id="${[...bookmarks.keys()].indexOf(id)+1}" w:name="${b}"/>`:''}${runs(value)}${b?`<w:bookmarkEnd w:id="${[...bookmarks.keys()].indexOf(id)+1}"/>`:''}</w:p>`;}).join('');
 const ns='xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"';
 const fonts='<w:rFonts w:ascii="Times New Roman" w:hAnsi="Times New Roman" w:eastAsia="SimSun"/>';
 return zipFiles({'[Content_Types].xml':`<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/><Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/></Types>`,
 '_rels/.rels':'<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>',
 'word/document.xml':`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document ${ns}><w:body>${body}<w:sectPr><w:footerReference w:type="default" r:id="footer"/><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1417" w:right="1417" w:bottom="1417" w:left="1417" w:header="600" w:footer="600"/><w:docGrid w:linePitch="440"/></w:sectPr></w:body></w:document>`,
 'word/styles.xml':`<?xml version="1.0"?><w:styles ${ns}><w:docDefaults><w:rPrDefault><w:rPr>${fonts}<w:sz w:val="24"/><w:lang w:val="en-US" w:eastAsia="zh-CN"/></w:rPr></w:rPrDefault><w:pPrDefault><w:pPr><w:spacing w:after="80" w:line="440" w:lineRule="exact"/><w:widowControl/><w:wordWrap w:val="1"/></w:pPr></w:pPrDefault></w:docDefaults><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/><w:pPr><w:ind w:firstLine="480"/></w:pPr></w:style><w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:pPr><w:jc w:val="center"/><w:keepNext/><w:spacing w:before="0" w:after="240" w:line="600" w:lineRule="atLeast"/></w:pPr><w:rPr><w:rFonts w:eastAsia="SimHei"/><w:b/><w:sz w:val="36"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:pPr><w:keepNext/><w:spacing w:before="200" w:after="100"/><w:outlineLvl w:val="0"/></w:pPr><w:rPr><w:rFonts w:eastAsia="SimHei"/><w:b/><w:sz w:val="28"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="heading 2"/><w:pPr><w:keepNext/><w:spacing w:before="140" w:after="80"/><w:outlineLvl w:val="1"/></w:pPr><w:rPr><w:rFonts w:eastAsia="SimHei"/><w:b/><w:sz w:val="24"/></w:rPr></w:style></w:styles>`,
 'word/footer1.xml':`<?xml version="1.0"?><w:ftr ${ns}><w:p><w:pPr><w:jc w:val="center"/></w:pPr><w:r><w:fldChar w:fldCharType="begin"/></w:r><w:r><w:instrText> PAGE </w:instrText></w:r><w:r><w:fldChar w:fldCharType="end"/></w:r></w:p></w:ftr>`,
 'word/_rels/document.xml.rels':`<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="styles" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/><Relationship Id="footer" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" Target="footer1.xml"/>${relations.map(r=>`<Relationship Id="${r.id}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="${xml(r.url)}" TargetMode="External"/>`).join('')}</Relationships>`});
}
