'use client';
import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Search,FlaskConical,ArrowUpRight,Download,Upload,BookOpen,FileText,Layers3,SlidersHorizontal,Check,RotateCcw,ChevronRight,History,Database,Link2,Plus,X} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Switch} from '@/components/ui/switch';
import {Button} from '@/components/ui/button';
import {Toaster,toast} from 'sonner';
import snapshot from '@/data/patent_records.json';
import {buildStrategy,createTask,normalizeRecords,restoreWorkspace,parseImport,refineTask,reportMarkdown,saveReport,externalSearchURL,DATA_MODES} from '@/core/engine.mjs';
import {markdownToDocx} from '@/core/docx.mjs';
const DEFAULT='液氢储罐压力调节方案探索';
const STORAGE='patent-lab.workspace.v1';
const blankEdit={title:'',introduction:'',conclusion:''};
function download(name:string,content:any,type='text/plain;charset=utf-8'){const form=document.createElement('form');form.method='POST';form.action='/api/export';form.style.display='none';let encoding='utf8',payload=content;if(content instanceof Uint8Array){encoding='base64';let binary='';for(let i=0;i<content.length;i+=8192)binary+=String.fromCharCode(...content.subarray(i,i+8192));payload=btoa(binary);}for(const [key,value]of Object.entries({filename:name,content:String(payload),encoding,type})){const input=document.createElement('input');input.type='hidden';input.name=key;input.value=value;form.appendChild(input);}document.body.appendChild(form);form.submit();setTimeout(()=>form.remove(),10000);}
function Badge({children,tone=''}:{children:React.ReactNode,tone?:string}){return <span className={`badge ${tone}`}>{children}</span>;}
export default function Home(){
 const [topic,setTopic]=useState(DEFAULT),[strategy,setStrategy]=useState<any>(()=>buildStrategy(DEFAULT)),[dataset,setDataset]=useState<any>(()=>normalizeRecords(snapshot,'public_snapshot'));
 const [task,setTask]=useState<any>(null),[tab,setTab]=useState('records'),[learning,setLearning]=useState(true),[detail,setDetail]=useState<any>(null),[excluded,setExcluded]=useState<string[]>([]),[notes,setNotes]=useState<Record<string,string>>({}),[edit,setEdit]=useState(blankEdit),[history,setHistory]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(''),[ready,setReady]=useState(false),[quiz,setQuiz]=useState(''),[answered,setAnswered]=useState(false),[feedback,setFeedback]=useState('');
 const file=useRef<HTMLInputElement>(null),backup=useRef<HTMLInputElement>(null),restoreDone=useRef(false);
 useEffect(()=>{if(restoreDone.current)return;restoreDone.current=true;try{const raw=localStorage.getItem(STORAGE);if(raw){const s=restoreWorkspace(raw,snapshot);if(s){setTopic(s.topic);setStrategy(s.strategy);setDataset(s.dataset);setTask(s.task||null);setExcluded(s.excluded||[]);setNotes(s.notes as Record<string,string>);setEdit(s.edit as typeof blankEdit);setLearning(s.learning!==false);setSaved('已恢复本机任务');}}}catch{setError('本机任务无法恢复，可重新选择示例或载入任务备份。');}setReady(true);},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(STORAGE,JSON.stringify({schema:1,topic,strategy,dataset,task,excluded,notes,edit,learning}));setSaved('已保存到此浏览器');}catch{setSaved('本机存储空间不足，请导出任务备份');}},[ready,topic,strategy,dataset,task,excluded,notes,edit,learning]);
 const current=useMemo(()=>task?refineTask(task,excluded,notes):null,[task,excluded,notes]);
 const report=useMemo(()=>current?reportMarkdown(current,edit):'', [current,edit]);
 function run(nextStrategy=strategy,nextData=dataset,nextTopic=topic){try{if(nextStrategy.topic!==nextTopic){nextStrategy=buildStrategy(nextTopic);setStrategy(nextStrategy);}const next=createTask(nextTopic,nextData,nextStrategy,task?.topic===nextTopic?task:null);setTask(next);setExcluded([]);setNotes({});setTab('records');setError('');toast.success(`已筛选 ${next.stats.count} 条记录`);return next;}catch(e:any){setError(e.message);toast.error(e.message);return null;}}
 function example(value:string){const s=buildStrategy(value);setTopic(value);setStrategy(s);setDataset(normalizeRecords(snapshot,'public_snapshot'));setTask(null);setExcluded([]);setNotes({});setEdit(blankEdit);setQuiz('');setAnswered(false);setError('');}
 function exportReport(format:string){try{if(!current)return;const next=saveReport(current,edit);setTask({...task,report_versions:next.report_versions});const frozen=next.report_versions.at(-1).markdown;const name=`专利情报_${current.task_id}_v${next.report_versions.length}`;if(format==='docx')download(`${name}.docx`,markdownToDocx(frozen),'application/vnd.openxmlformats-officedocument.wordprocessingml.document');else if(format==='md')download(`${name}.md`,frozen);else download(`${name}.json`,JSON.stringify(next,null,2),'application/json');toast.success('报告版本已保存，已提交文件下载请求');}catch(e:any){setError(e.message);}}
 async function importFile(f:File){try{if(f.size>4*1024*1024)throw Error('文件超过 4 MB，请拆分后导入');const d=parseImport(await f.text(),f.name);setDataset(d);setTask(null);setExcluded([]);setNotes({});setError('');toast.success(`导入 ${d.unique_count} 条，去重 ${d.duplicate_count} 条`);}catch(e:any){setError(e.message);}finally{if(file.current)file.current.value='';}}
 function backUp(){download('专利情报_任务备份.json',JSON.stringify({schema:1,topic,strategy,dataset,task,excluded,notes,edit,learning},null,2),'application/json');}
 async function restore(f:File){try{if(f.size>8*1024*1024)throw Error('备份超过 8 MB');const s=restoreWorkspace(await f.text(),snapshot);setDataset(s.dataset);setTopic(s.topic);setStrategy(s.strategy);setTask(s.task);setEdit(s.edit as typeof blankEdit);setExcluded(s.excluded);setNotes(s.notes as Record<string,string>);setLearning(s.learning);setError('');toast.success('已恢复任务、筛选理由和报告版本；当前分析已重新校验');}catch(e:any){setError(e.message);}finally{if(backup.current)backup.current.value='';}}
 const stateRef=useRef<any>(null);stateRef.current={topic,strategy,dataset,task};
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();Promise.resolve(ctx.registerTool({name:'create_patent_exploration',title:'创建专利探索任务',description:'在本页公开快照或已导入样本中使用规则筛选主题并创建可追溯任务。不会实时检索数据库。',inputSchema:{type:'object',properties:{topic:{type:'string',minLength:1,maxLength:500}},required:['topic'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:any)=>{if(typeof input?.topic!=='string'||!input.topic.trim()||input.topic.length>500)throw Error('请输入1至500字主题');const s=buildStrategy(input.topic),t=createTask(input.topic,stateRef.current.dataset,s);setTopic(input.topic);setStrategy(s);setTask(t);setExcluded([]);setNotes({});setTab('records');return {task_id:t.task_id,count:t.stats.count,data_mode:t.data_mode,inference_mode:t.inference_mode};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[]);
 const dirty=task&&(topic!==task.topic||JSON.stringify({...strategy,topic})!==JSON.stringify(task.query.strategy));
 return <div className="workspace"><Toaster position="bottom-right"/><header className="topbar"><a className="brand" href="/" aria-label="专利研习首页"><span className="brand-icon"><FlaskConical size={23}/></span><strong>专利研习<span>PATENT LAB</span></strong></a><div className="top-status"><span>科研主题探索</span><Badge>原型 v0.1</Badge></div><div className="top-actions"><span className="saved">{saved||'本机工作区'}</span><Button variant="outline" onClick={backUp}><Download size={15}/>任务备份</Button></div></header>
 <div className="page-heading"><div><div className="eyebrow">RESEARCH WORKSPACE</div><h1>从研究问题，到有据可查的技术方案</h1><p>构造检索策略，阅读代表专利，保留你的研究判断。</p></div><div className="mode-control"><BookOpen size={17}/><label htmlFor="learning">学习模式</label><Switch id="learning" checked={learning} onCheckedChange={setLearning}/></div></div>
 <div className="layout"><aside className="strategy-panel"><div className="panel-heading"><h2><SlidersHorizontal size={18}/>研究与检索</h2><span className="step-number">01</span></div>
 <label className="field-label" htmlFor="topic">研究主题</label><textarea id="topic" className="topic-input" value={topic} onChange={e=>setTopic(e.target.value)} placeholder="例如：液氢储罐如何调节压力？" maxLength={500}/>
 <div className="examples"><button onClick={()=>example(DEFAULT)}>液氢储罐</button><button onClick={()=>example('锂电池液冷结构探索')}>电池液冷</button></div>
 <Button variant="outline" className="full" onClick={()=>{try{setStrategy(buildStrategy(topic));setError('');}catch(e:any){setError(e.message);}}}><Plus size={15}/>依据主题更新检索词</Button>
 <div className="separator"/>
 <label className="field-label" htmlFor="objects">技术对象词 <span>组内任一命中</span></label><textarea id="objects" rows={2} value={strategy.object_terms.join(', ')} onChange={e=>setStrategy({...strategy,object_terms:e.target.value.split(/[,，]/)})}/>
 <label className="field-label" htmlFor="focus">重点词 <span>可留空</span></label><textarea id="focus" rows={3} value={strategy.focus_terms.join(', ')} onChange={e=>setStrategy({...strategy,focus_terms:e.target.value.split(/[,，]/)})}/>
 <label className="field-label" htmlFor="exclude">排除词</label><input id="exclude" value={strategy.exclude_terms.join(', ')} onChange={e=>setStrategy({...strategy,exclude_terms:e.target.value.split(/[,，]/)})} placeholder="逗号分隔，如：vehicle"/>
 <div className="dates"><div><label className="field-label" htmlFor="from">公开日起</label><input id="from" type="date" value={strategy.from||''} onChange={e=>setStrategy({...strategy,from:e.target.value||null})}/></div><div><label className="field-label" htmlFor="to">公开日止</label><input id="to" type="date" value={strategy.to||''} onChange={e=>setStrategy({...strategy,to:e.target.value||null})}/></div></div>
 <label className="checkbox-label"><Checkbox checked={strategy.include_unknown_dates} onCheckedChange={v=>setStrategy({...strategy,include_unknown_dates:!!v})}/>保留日期缺失记录</label>
 <div className="source-select"><label className="field-label" htmlFor="source">数据来源</label><Select value={dataset.data_mode==='public_snapshot'?'snapshot':'import'} onValueChange={v=>{if(v==='snapshot'){setDataset(normalizeRecords(snapshot,'public_snapshot'));setTask(null);}else file.current?.click();}}><SelectTrigger id="source" className="full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="snapshot">公开记录快照 · 8 条</SelectItem><SelectItem value="import">导入自己的 JSON / CSV</SelectItem></SelectContent></Select></div>
 <input ref={file} type="file" accept=".json,.csv" className="sr-only" aria-label="导入专利文件" onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/><input ref={backup} type="file" accept=".json" className="sr-only" aria-label="载入任务备份" onChange={e=>e.target.files?.[0]&&restore(e.target.files[0])}/>
 <div className="source-actions"><button onClick={()=>file.current?.click()}><Upload size={14}/>导入记录</button><button onClick={()=>download('专利导入模板.csv','publication_number,title,abstract_excerpt,applicants,publication_date,source_url,language\n','text/csv;charset=utf-8')}>下载模板</button></div>
 <Button className="run-button full" onClick={()=>run()}><Search size={18}/>运行检索与整理<ChevronRight size={17}/></Button>
 <p className="hint">在当前载入样本中筛选；逗号分词，组内 OR、两组 AND。</p>
 {learning&&<div className="learn-tip"><BookOpen size={16}/><div><strong>为什么需要扩词？</strong><p>{strategy.rationale}</p></div></div>}
 <button className="backup-link" onClick={()=>backup.current?.click()}><RotateCcw size={14}/>载入已有任务备份</button>
 </aside>
 <main className="main-work"><div className="provenance"><div><Database size={18}/><strong>{DATA_MODES[dataset.data_mode as keyof typeof DATA_MODES]}</strong><span>{dataset.unique_count} 条载入 · {dataset.duplicate_count} 条重复</span></div><Badge tone="blue">规则处理 · 未调用模型</Badge></div>
 {dataset.warnings?.length>0&&<div className="pending">{dataset.warnings.map((w:any,i:number)=><p key={i}>{w.publication_number}：{w.message}</p>)}</div>}<p className="provenance-note">{dataset.data_mode==='public_snapshot'?'快照核验于 2026-09-12，仅含必要短摘录与来源链接。':'导入数据由用户提供，来源与内容尚未独立核验。'} 当前功能不包含实时全库检索。</p>
 {error&&<div className="error" role="alert"><strong>请检查输入</strong><p>{error}</p><button aria-label="关闭错误" onClick={()=>setError('')}><X size={16}/></button></div>}
 {dirty&&<div className="pending">检索条件有修改。点击左侧运行按钮后，结果与报告将使用新条件；报告补充说明会保留。</div>}
 {!task?<section className="start-panel"><div className="start-symbol"><Search size={30}/></div><div className="eyebrow">你的第一项探索任务</div><h2>{topic}</h2><p>当前载入 {dataset.unique_count} 条记录。运行左侧检索，查看与你的主题匹配的结构与过程证据；材料不足时可导入相关公开记录。</p><div className="flow-cards"><div><span>01</span><strong>明确检索范围</strong><p>调整对象词和重点词</p></div><div><span>02</span><strong>阅读与选择证据</strong><p>说明保留或排除的理由</p></div><div><span>03</span><strong>形成探索记录</strong><p>导出可编辑的研究材料</p></div></div><Button onClick={()=>run()}>运行当前主题<Search size={16}/></Button><p className="small-note">任何新主题都将使用自己的检索词；缺少相应数据时会显示无结果。</p></section>:<>
 <div className="results-heading"><div><div className="eyebrow">EXPLORATION RESULTS / V{task.version}</div><h2>{task.topic}</h2></div><Button variant="ghost" onClick={()=>setHistory(true)}><History size={17}/>查询记录</Button></div>
 <div className="stats"><div><span>当前保留</span><strong>{current.stats.count}<small> 条记录</small></strong></div><div><span>原文证据</span><strong>{current.stats.evidence_count}<small> 个片段</small></strong></div><div><span>初步方案分组</span><strong>{current.analysis.groups.length}<small> 组</small></strong></div><div><span>缺少权利要求</span><strong>{current.stats.missing_claims}<small> 条</small></strong></div></div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="work-tabs" variant="line"><TabsTrigger value="records"><FileText size={17}/>专利记录</TabsTrigger><TabsTrigger value="routes"><Layers3 size={17}/>技术方案</TabsTrigger><TabsTrigger value="report"><BookOpen size={17}/>探索报告</TabsTrigger>{learning&&<TabsTrigger value="learn">学习检验</TabsTrigger>}</TabsList>
 <TabsContent value="records"><div className="list-toolbar"><span>按词项命中排序 · {task.records.length} 条匹配，{excluded.length} 条排除</span><a target="_blank" rel="noreferrer" href={externalSearchURL(task.query.strategy)}>扩展检索（仅词项，日期另设）<ArrowUpRight size={14}/></a></div>
 {!task.records.length&&<div className="empty-state"><Search size={30}/><h3>当前样本没有匹配记录</h3><p>减少重点词或放宽日期范围，也可以导入与主题相关的专利。当前没有可支持技术方案判断的材料。</p><Button variant="outline" onClick={()=>file.current?.click()}>导入相关材料</Button></div>}
 {task.records.map((r:any,i:number)=><article key={r.record_id} className={`patent-card ${excluded.includes(r.record_id)?'excluded':''}`}><div className="record-index">{String(i+1).padStart(2,'0')}</div><div className="record-content"><div className="record-top"><span className="patent-number">{r.publication_number}</span><span>{r.publication_date||'日期缺失'}</span><Badge>{DATA_MODES[r.data_mode as keyof typeof DATA_MODES]}</Badge></div><h3><button onClick={()=>setDetail(r)}>{r.title}</button></h3><p className="record-summary">{r.summary_zh||r.abstract_excerpt||'当前仅有元数据，请补充原文。'}</p><div className="record-meta"><span>{r.applicants.join('、')||'原始申请人缺失'}</span><span>{r.evidence.length} 条原文片段</span></div><div className="record-footer"><div className="term-tags">{r.match_terms.slice(0,4).map((v:string)=><span key={v}>{v}</span>)}</div><button className="evidence-button" onClick={()=>setDetail(r)}>查看证据<ChevronRight size={15}/></button></div><details><summary>记录我的筛选理由</summary><textarea aria-label={`${r.publication_number}筛选理由`} placeholder="这条记录为何与研究问题相关？" value={notes[r.record_id]||''} onChange={e=>setNotes({...notes,[r.record_id]:e.target.value})}/></details></div><label className="keep-record"><Checkbox aria-label={`保留${r.publication_number}`} checked={!excluded.includes(r.record_id)} onCheckedChange={v=>setExcluded(v?excluded.filter(x=>x!==r.record_id):[...excluded,r.record_id])}/><span>保留</span></label></article>)}
 </TabsContent>
 <TabsContent value="routes"><div className="section-intro"><h3>从可见材料归纳技术方案</h3><p>分组依据原文中的结构与过程词。同一记录可进入多个组；相似标题不用于合并专利族。</p></div><div className="route-grid">{current.analysis.groups.map((g:any)=><section className="route-card" key={g.group_id}><Badge>{g.record_ids.length} 条记录</Badge><h3>{g.label}</h3><p>{g.reason}</p>{g.record_ids.map((id:string)=>{const r=current.records.find((r:any)=>r.record_id===id);return <button key={id} onClick={()=>setDetail(r)}><FileText size={15}/>{r.publication_number}<ChevronRight size={14}/></button>;})}</section>)}</div><div className="question-box"><h3>下一步可以验证什么？</h3>{current.analysis.opportunities.length?current.analysis.opportunities.map((q:any)=><p key={q.claim_id}>{q.text}</p>):<p>现有证据不足，请补充相关记录及原文后提出问题。</p>}</div><div className="mini-stats"><h3>样本公开年份</h3>{Object.entries(current.stats.years).sort().map(([y,n]:any)=><div key={y}><span>{y}</span><div className="bar-track"><i style={{width:`${n/Math.max(current.stats.count,1)*100}%`}}/></div><strong>{n} 条</strong></div>)}<p>按当前保留公开记录计数，不表示领域规模或申请趋势。</p></div></TabsContent>
 <TabsContent value="report"><div className="report-toolbar"><div><h3>探索报告</h3><p>补充你的判断，再导出可编辑材料。</p></div><div><Button variant="outline" onClick={()=>exportReport('md')}>Markdown</Button><Button variant="outline" onClick={()=>exportReport('json')}>证据 JSON</Button><Button onClick={()=>exportReport('docx')}><Download size={16}/>导出 Word</Button></div></div><div className="report-editor"><label htmlFor="report-title">报告标题</label><input id="report-title" placeholder={`${task.topic}：专利情报探索记录`} value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/><label htmlFor="introduction">研究背景与约束 <Badge>用户编辑</Badge></label><textarea id="introduction" value={edit.introduction} onChange={e=>setEdit({...edit,introduction:e.target.value})} placeholder="补充你关注的设备、工况与比较目标"/><label htmlFor="conclusion">我的研究判断 <Badge>待核验</Badge></label><textarea id="conclusion" value={edit.conclusion} onChange={e=>setEdit({...edit,conclusion:e.target.value})} placeholder="依据哪些证据形成判断？哪些问题还需验证？"/><p>补充内容会随查询调整保留。每次导出记录报告版本；自动整理的事实与引用单独保留。</p></div><div className="report-paper">{report.split('\n').filter(Boolean).map((line:string,i:number)=>line.startsWith('# ')?<h2 key={i}>{line.slice(2)}</h2>:line.startsWith('## ')?<h3 key={i}>{line.slice(3)}</h3>:line.startsWith('### ')?<h4 key={i}>{line.slice(4)}</h4>:<p key={i}>{line.split(/(\[ev-[^\]]+\])/g).map((v,j)=>{const id=v.match(/^\[(ev-[^\]]+)\]$/)?.[1];const r=id&&current.records.find((r:any)=>r.evidence.some((e:any)=>e.evidence_id===id));return r?<button className="citation" key={j} onClick={()=>setDetail(r)}>{v}</button>:v;})}</p>)}</div><p className="small-note">已保存 {task.report_versions.length} 个导出版本；导出的数据模式、查询版本与当前预览一致。</p></TabsContent>
 <TabsContent value="learn"><section className="learning-card"><Badge>证据意识 · 1 / 1</Badge><h3>只有摘要或说明书短摘录时，能够作出哪项判断？</h3><div className="quiz-options">{[['a','确定某个方案可以自由实施'],['b','描述片段中明确出现的结构，并说明材料不足'],['c','证明本领域已经不存在其他技术路线']].map(([id,label])=><button key={id} className={quiz===id?'chosen':''} onClick={()=>{setQuiz(id);setAnswered(false);}}>{id.toUpperCase()}. {label}</button>)}</div><Button disabled={!quiz} onClick={()=>setAnswered(true)}>检查理解</Button>{answered&&<div className="quiz-feedback">{quiz==='b'?'判断正确。':'请再看一次材料范围。'}短摘录可以支持其明确表达的技术要素。保护范围、自由实施与完整技术覆盖需要另外取得材料并开展专业分析。</div>}<label className="field-label" htmlFor="feedback">记录本次操作中最难理解的一步</label><textarea id="feedback" value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="请写具体步骤或证据问题，无需填写姓名"/><Button variant="outline" disabled={!feedback.trim()} onClick={()=>download('匿名学习反馈.json',JSON.stringify({created_at:new Date().toISOString(),task_id:task.task_id,feedback,quiz_answer:quiz,quiz_checked:answered,note:'本机用户主动导出的反馈；未自动上传'},null,2),'application/json')}>导出匿名反馈</Button><p>练习结果用于自查，尚未证明学习效果；反馈只在本机导出。</p></section></TabsContent>
 </Tabs>
 <div className="workspace-footnote"><Link2 size={15}/><p>结论范围限于已取得材料。原始申请人、当前权利人及法律状态需要分别核验。</p></div></>}
 </main></div>
 <Dialog open={!!detail} onOpenChange={open=>!open&&setDetail(null)}><DialogContent className="evidence-dialog"><DialogHeader><DialogTitle>原文证据</DialogTitle><DialogDescription>{detail?.publication_number} · {detail?.content_scope}</DialogDescription></DialogHeader>{detail&&<div className="evidence-scroll"><h3>{detail.title}</h3><div className="evidence-meta"><Badge>{DATA_MODES[detail.data_mode as keyof typeof DATA_MODES]}</Badge><span>核验/取得：{detail.retrieved_at||'未提供'}</span></div>{detail.evidence.length?detail.evidence.map((e:any)=><section className="excerpt" key={e.evidence_id}><span className="evidence-id">{e.evidence_id}</span><blockquote>{e.text}</blockquote><p><strong>原文定位：</strong>{e.locator}</p><p><strong>语言与校验：</strong>{e.language} · {e.translated?'译文':'原文'} · {e.checksum}</p></section>):<p>缺少原文片段，无法建立内容结论。</p>}{detail.summary_zh&&<div className="translation"><strong>人工中文转述</strong><p>{detail.summary_zh}</p></div>}<p className="boundary">现有片段支持其明确出现的结构或过程。{detail.claims?'已显示用户提供的权利要求，完整性和来源需核验。':'完整权利要求尚未取得。'}专利族与法律状态尚未核验。</p>{detail.source_url?<a className="source-link" href={detail.source_url} target="_blank" rel="noreferrer">打开原始专利页面<ArrowUpRight size={17}/></a>:<p>来源链接未提供，请补充后核验。</p>}</div>}</DialogContent></Dialog>
 <Dialog open={history} onOpenChange={setHistory}><DialogContent className="history-dialog"><DialogHeader><DialogTitle>查询与导出记录</DialogTitle><DialogDescription>修改检索条件形成新版本，点击回填可重新运行；报告编辑内容保留。</DialogDescription></DialogHeader><div className="history-list">{task?.query_history.map((q:any)=><section key={q.version}><strong>查询 v{q.version} · {q.returned_count} 条</strong><p>{q.query}</p><small>{q.created_at}</small><Button variant="outline" onClick={()=>{setStrategy(q.strategy);setTopic(task.topic);setHistory(false);}}>回填此版条件</Button></section>)}{task?.report_versions.map((r:any)=><section key={r.report_id}><strong>报告 v{r.version} · 查询 v{r.query_version}</strong><p>{r.user_edited?'含用户编辑':'自动整理'}{r.origin==='restored_replay'?' · 备份已有结果回放':''}</p><Button variant="outline" onClick={()=>download(`历史报告_v${r.version}.md`,r.markdown)}>下载此版</Button></section>)}</div></DialogContent></Dialog>
 </div>;
}
