'use client';
import React,{useState,useEffect,useRef} from 'react';
import {compileQuery} from '../core/query.mjs';
export async function api(path:string,method='GET',data?:any):Promise<any>{const r=await fetch(path,{method,headers:method==='GET'?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const value:any=await r.json();if(!r.ok)throw Error(value.error?.message||'本机服务请求失败');return value;}
const labels:any={queued:'排队',retrieving:'检索与读取原文',analyzing:'AI 分析',completed:'完成',partial:'部分完成',failed:'失败',cancelled:'已取消',cancelling:'正在取消',interrupted:'服务中断'};
const busy=(s:string)=>['queued','retrieving','analyzing','cancelling'].includes(s);
export default function LivePanel({topic,strategy,current,onStrategy,onTask,onError}:any){
 const [status,setStatus]=useState<any>(null),[run,setRun]=useState<any>(null),[provider,setProvider]=useState('codex'),[query,setQuery]=useState(''),[settings,setSettings]=useState(false),[key,setKey]=useState(''),[keyProvider,setKeyProvider]=useState('patentics'),[pending,setPending]=useState(false),[runs,setRuns]=useState<any[]>([]);const received=useRef('');const callbacks=useRef({onTask,onStrategy,onError});callbacks.current={onTask,onStrategy,onError};
 useEffect(()=>{try{setQuery(compileQuery(strategy,topic));}catch{setQuery('');}},[topic,strategy]);
 async function refresh(){const s=await api('/api/status');setStatus(s);const list=await api('/api/runs');setRuns(list);return s;}
 useEffect(()=>{let alive=true;refresh().then(async s=>{const id=s.active_run;if(id&&alive)setRun(await api('/api/runs/'+id));}).catch(e=>callbacks.current.onError(e.message));return()=>{alive=false;};},[]);
 useEffect(()=>{const timer=setInterval(()=>refresh().catch(()=>{}),5000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(!run)return;localStorage.setItem('patent-lab.active-run',run.run_id);let stopped=false;const accept=(r:any)=>{setRun(r);if(r.task&&received.current!==r.run_id+':'+r.status&&!busy(r.status)){received.current=r.run_id+':'+r.status;callbacks.current.onTask(r.task);}if(r.strategy&&r.status==='completed'&&received.current!==r.run_id){received.current=r.run_id;callbacks.current.onStrategy(r.strategy);}if(!busy(r.status))refresh().catch(()=>{});};if(!busy(run.status)){accept(run);return;}const timer=setInterval(()=>api('/api/runs/'+run.run_id).then(r=>!stopped&&accept(r)).catch(e=>callbacks.current.onError(e.message)),1500);return()=>{stopped=true;clearInterval(timer);};},[run?.run_id,run?.status]);
 async function start(kind:string){setPending(true);try{const r=await api('/api/runs','POST',{kind,topic,strategy:{...strategy,topic},provider,query_override:query,database:'cnapp',...(kind==='analyze'?{task:current}:{})});setRun(r);onError('');}catch(e:any){onError(e.message);}finally{setPending(false);}}
 const active=pending||busy(run?.status)||!!status?.active_run;
 return <section className="live-panel" aria-label="真实检索与分析"><div className="panel-heading"><h2>本机真实检索与 AI</h2><button onClick={()=>setSettings(!settings)}>服务配置</button></div><p>Patentics · 中国库 cnapp · 前 20 条候选，顺序取得最多 5 篇可用详情。</p><label className="field-label" htmlFor="model-provider">分析服务</label><select id="model-provider" value={provider} onChange={e=>setProvider(e.target.value)} disabled={active}><option value="codex">Codex · gpt-6-astra</option><option value="glm">智谱 · glm-4.7-flash</option></select><p className="hint">{status?`Codex：${status.providers.codex.state==='verified'?'已成功生成':status.providers.codex.state==='ready'?'本机版本可用，等待调用验证':'不可用'}；智谱：${status.providers.glm.state==='verified'?'已成功生成':'尚未成功联调'}。失败时保留资料，可明确重试。`:'正在核验本机服务…'}</p>
 {settings&&<div className="settings-box"><p>凭据仅送至本机服务，以当前 Windows 用户 DPAPI 加密保存。</p><label htmlFor="credential-provider">凭据所属服务</label><select id="credential-provider" value={keyProvider} onChange={e=>setKeyProvider(e.target.value)}><option value="patentics">Patentics 网关</option><option value="glm">智谱</option></select><label htmlFor="api-key">API Key</label><input id="api-key" type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)}/><button disabled={!key||pending} onClick={async()=>{setPending(true);try{await api('/api/settings','POST',{provider:keyProvider,key});setKey('');await refresh();setSettings(false);}catch(e:any){onError(e.message);}finally{setPending(false);}}}>加密保存</button><p>{status?.credentials?.patentics?.configured?'Patentics 已配置':'Patentics 未配置'} · {status?.credentials?.glm?.configured?'智谱已配置':'智谱未配置'}</p></div>}
 <button disabled={active} onClick={()=>start('strategy')}>AI 辅助生成检索策略</button><label className="field-label" htmlFor="actual-query">可编辑的 Patentics 检索式</label><textarea id="actual-query" rows={4} value={query} onChange={e=>setQuery(e.target.value)} disabled={active}/><p className="hint">上方词项变化会重新编译此式。手工修改检索式后，以此处实际请求为准；本地词项用于阅读提示。</p><div className="live-actions"><button className="primary" disabled={active||!query} onClick={()=>start('search')}>真实检索并分析</button><button disabled={active||!current?.records.length} onClick={()=>start('analyze')}>按当前保留记录重新分析</button></div>
 {run&&<div className="run-progress" role="status"><strong>{labels[run.status]||run.status}</strong><p>{run.input.topic} · 数据请求 {run.api_calls}/20 · 已取得 {run.acquired?.length||run.task?.records.length||0}/5 篇 · 模型调用 {run.model_calls}</p>{run.error&&<p>{run.error.message}</p>}{run.warnings?.map((w:any,i:number)=><p key={i}>{w.message}</p>)}{busy(run.status)?<button onClick={()=>api(`/api/runs/${run.run_id}/cancel`,'POST',{}).then(setRun).catch(e=>onError(e.message))}>取消任务</button>:['failed','partial','cancelled','interrupted'].includes(run.status)&&<button disabled={active} onClick={()=>api(`/api/runs/${run.run_id}/retry`,'POST',{}).then(setRun).catch(e=>onError(e.message))}>明确重试未完成阶段</button>}</div>}
 {!!runs.length&&<details><summary>本机运行记录</summary>{runs.slice(0,12).map(r=><button className="run-history" key={r.run_id} disabled={active} onClick={()=>{received.current='';api('/api/runs/'+r.run_id).then(setRun).catch(e=>onError(e.message));}}>{r.topic} · {labels[r.status]}</button>)}</details>}
 </section>;
}
